### PR TITLE
[14.0][MIG] pos_product_template: Migration to 14.0

### PR DESCRIPTION
**Pull request by pedroguirao**
New PR from #750 with correct format-patch

### CODE REVIEW

**Review by francesco-ooops — APPROVED** [review]
Functional review ok

Compared to v.12 I liked the fact that you could see how many variants there were for each attribute value, but it's not a blocking issue

image

**Comment by francesco-ooops** [comment]
@OCA/pos-maintainers could you review?

**Review by ivantodorovich — CHANGES_REQUESTED** [review]
Code review only, LG.
I bit hard to review with all the cosmetic changes in the Migration commits 😢

If you had the time, would be great to squash cosmetic changes in `[IMP] pos_product_template: black, isort, prettier` and keep only actual migration changes in `[MIG] pos_product_template: Migration to 14.0` commit.

There are, however, 2 migration to 14.0 commits. It kind of seems the second one is the one with more cosmetic changes. The point is, we'd like to have a meaninful commit history. Could you maybe squash them, or reword them in a way that makes sense?

**Review by SicurSam — APPROVED** [review]
Functional review ok

**Comment by francesco-ooops** [comment]
> Code review only, LG. I bit hard to review with all the cosmetic changes in the Migration commits 😢
> 
> If you had the time, would be great to squash cosmetic changes in `[IMP] pos_product_template: black, isort, prettier` and keep only actual migration changes in `[MIG] pos_product_template: Migration to 14.0` commit.
> 
> There are, however, 2 migration to 14.0 commits. It kind of seems the second one is the one with more cosmetic changes. The point is, we'd like to have a meaninful commit history. Could you maybe squash them, or reword them in a way that makes sense?

@pedroguirao sorry to press you, can you update us on this?

**Comment by francesco-ooops** [comment]
@pedroguirao need any help?

**Comment by pedroguirao** [comment]
@francesco-ooops @ivantodorovich 
Hi all, here as always a bit busy with work, i made 
git rebase -i HEADE~3  and squashed the 3 commits in one, pls confirm that is that you are requiring from me. 

Thanks for the help!

**Comment by francesco-ooops** [comment]
Hi @pedroguirao, I think the request is to have

> cosmetic changes in [IMP] pos_product_template: black, isort, prettier and 
keep only actual migration changes in [MIG] pos_product_template: Migration to 14.0 commit.

**Comment by pedroguirao** [comment]
@ivantodorovich @francesco-ooops 

Hi again! i commited the migration changes in [MIG] pos_product_template: Migration to 14.0 as sugested, not sure about the cosmetic changes, i only have the [IMP] pos_product_template: black, isort, prettier

**Comment by francesco-ooops** [comment]
@ivantodorovich what do you say?

**Review by ivantodorovich — APPROVED** [review]
We still have cosmetic diffs in the migration commit.
But it's fine by me. In the future, though, please try to keep them separated 🙏🏻

**Pull request merged**
