### PR TITLE
Pos Sequence Ref Number v9

### PR DESCRIPTION
**Pull request by samirGuesmi**

### CODE REVIEW

**Comment by samirGuesmi** [comment]
any update?

**Comment by legalsylvain** [comment]
Hi @samirGuesmi thanks for your PR. CLA is OK.

About your PR, a general good pratice is to cherry-pick commits from the previous version. (here V8) and to make after the required changes in a separate commit. It helps reviewers to check more easily changes. 
You can also read this good how here : 
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0#technical-method-to-migrate-a-module-from-80-to-90-branch

About the PR, maybe the initial commiters could take a look ? 
@jbeficent, @rafaelbn, @yelizariev , @antespi 

kind regards.

**Comment by legalsylvain** [comment]
Hi @samirGuesmi did you took the time to check how cherry pick works ? 

regards.

**Comment by legalsylvain** [comment]
closing, due to inactivity. Feel free to reopen.

**Pull request closed without merging**
