### PR TITLE
[12.0] FIX pos_partner_firstname allowing non admin users to get partner_names_order from POS frontend

### PR DESCRIPTION
**Pull request by eLBati**
Otherwise they would get access error on ir.config_parameter

Steps:

 - Create a user POS manager without administration rights
 - Using that user, open POS frontend

### CODE REVIEW

**Review by mrcast — APPROVED** [review]
Functional test ok.
Thanks

**Review by legalsylvain — APPROVED** [review]
thanks for the patch.

/ocabot merge minor

**Comment by eLBati** [comment]
I think you need to run `/ocabot merge minor` in a separate message.
Thanks

**Pull request merged**
