### PR TITLE
[MIG] Backported pos_pricelist from 10.0 to 9.0

### PR DESCRIPTION
**Pull request by wpichler**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please respect commit history.

**Comment by rafaelbn** [comment]
Hi @wpichler thank! for this work! Please you have duplicated this PR with https://github.com/OCA/pos/pull/186 could you close one and the continue in the other? Thank you!!! smiley

**Comment by rafaelbn** [comment]
Thanks @wpichler for closing de other PR. As @pedrobaeza said. Please could you update this PR respecting commit history?

**Comment by houssine78** [comment]
Hi the other PR has been closed and this one doens't seem to go further. Does it condamned to be closed too?

**Comment by pedrobaeza** [comment]
If there's no fix on Travis status, I'm afraid so. You can retake the PR and fix it if you want, creating a new PR that superseeds this.

**Comment by houssine78** [comment]
thanks Pedro, that probably what we will do if we finally need it.

**Comment by pedrobaeza** [comment]
I close this one for now.

**Pull request closed without merging**
