### PR TITLE
[11.0] pos_cashier_login: use the default OCA icon

### PR DESCRIPTION
**Pull request by kirca**

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]
Hi @kirca. Generaly, self merging PR without review is not a good practice in OCA.

About that PR, LGTM. Thanks.

**Comment by kirca** [comment]
Hi @legalsylvain , I thought I can save some time and not have someone review since is just metafiles which I forgot to edit properly when initially contributing it. But you are right, this shouldn't be done in general. Thanks for taking the time to review and merge!

**Pull request merged**
