### PR TITLE
[FIX] pos_loyalty: frontend test failing in CI

### PR DESCRIPTION
**Pull request by kirca**

### CODE REVIEW

**Review by chienandalu — COMMENTED** [review]
No luck :disappointed:

**Comment by kirca** [comment]
Yeah, worth a try though :)

**Comment by rafaelbn** [comment]
Hi @kirca ,

We stil have CI red :red_circle:  in this branch.

CI was green :green_apple:  in this PR https://github.com/OCA/pos/pull/288 ?

2019-02-08 19:10:51,465 6513 INFO openerp_test odoo.addons.pos_loyalty.tests.test_pos_loyalty: ======================================================================
2019-02-08 19:10:51,465 6513 ERROR openerp_test odoo.addons.pos_loyalty.tests.test_pos_loyalty: FAIL: test_pos_loyalty (odoo.addons.pos_loyalty.tests.test_pos_loyalty.TestPOSLoyalty)
2019-02-08 19:10:51,465 6513 ERROR openerp_test odoo.addons.pos_loyalty.tests.test_pos_loyalty: Traceback (most recent call last):
2019-02-08 19:10:51,465 6513 ERROR openerp_test odoo.addons.pos_loyalty.tests.test_pos_loyalty: `   File "/home/travis/odoo-11.0/odoo/tests/common.py", line 362, in phantom_poll
2019-02-08 19:10:51,466 6513 ERROR openerp_test odoo.addons.pos_loyalty.tests.test_pos_loyalty: `     self.fail(pformat(json.loads(line[prefix:])))
2019-02-08 19:10:51,466 6513 ERROR openerp_test odoo.addons.pos_loyalty.tests.test_pos_loyalty: `   File "/opt/python/3.5.6/lib/python3.5/json/__init__.py", line 319, in loads
2019-02-08 19:10:51,466 6513 ERROR openerp_test odoo.addons.pos_loyalty.tests.test_pos_loyalty: `     return _default_decoder.decode(s)
2019-02-08 19:10:51,466 6513 ERROR openerp_test odoo.addons.pos_loyalty.tests.test_pos_loyalty: `   File "/opt/python/3.5.6/lib/python3.5/json/decoder.py", line 339, in decode
2019-02-08 19:10:51,466 6513 ERROR openerp_test odoo.addons.pos_loyalty.tests.test_pos_loyalty: `     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2019-02-08 19:10:51,467 6513 ERROR openerp_test odoo.addons.pos_loyalty.tests.test_pos_loyalty: `   File "/opt/python/3.5.6/lib/python3.5/json/decoder.py", line 357, in raw_decode
2019-02-08 19:10:51,467 6513 ERROR openerp_test odoo.addons.pos_loyalty.tests.test_pos_loyalty: `     raise JSONDecodeError("Expecting value", s, err.value) from None
2019-02-08 19:10:51,467 6513 ERROR openerp_test odoo.addons.pos_loyalty.tests.test_pos_loyalty: ` json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-02-08 19:10:51,468 6513 ERROR openerp_test odoo.addons.pos_loyalty.tests.test_pos_loyalty: `
2019-02-08 19:10:51,468 6513 ERROR openerp_test odoo.addons.pos_loyalty.tests.test_pos_loyalty: ` During handling of the above exception, another exception occurred:
2019-02-08 19:10:51,468 6513 ERROR openerp_test odoo.addons.pos_loyalty.tests.test_pos_loyalty: `
2019-02-08 19:10:51,469 6513 ERROR openerp_test odoo.addons.pos_loyalty.tests.test_pos_loyalty: ` Traceback (most recent call last):
2019-02-08 19:10:51,469 6513 ERROR openerp_test odoo.addons.pos_loyalty.tests.test_pos_loyalty: `   File "/home/travis/build/OCA/pos/pos_loyalty/tests/test_pos_loyalty.py", line 60, in test_pos_loyalty
2019-02-08 19:10:51,469 6513 ERROR openerp_test odoo.addons.pos_loyalty.tests.test_pos_loyalty: `     login="admin")
2019-02-08 19:10:51,469 6513 ERROR openerp_test odoo.addons.pos_loyalty.tests.test_pos_loyalty: `   File "/home/travis/odoo-11.0/odoo/tests/common.py", line 459, in phantom_js
2019-02-08 19:10:51,470 6513 ERROR openerp_test odoo.addons.pos_loyalty.tests.test_pos_loyalty: `     self.phantom_run(cmd, timeout)
2019-02-08 19:10:51,470 6513 ERROR openerp_test odoo.addons.pos_loyalty.tests.test_pos_loyalty: `   File "/home/travis/odoo-11.0/odoo/tests/common.py", line 386, in phantom_run
2019-02-08 19:10:51,470 6513 ERROR openerp_test odoo.addons.pos_loyalty.tests.test_pos_loyalty: `     result = self.phantom_poll(phantom, timeout)
2019-02-08 19:10:51,471 6513 ERROR openerp_test odoo.addons.pos_loyalty.tests.test_pos_loyalty: `   File "/home/travis/odoo-11.0/odoo/tests/common.py", line 364, in phantom_poll
2019-02-08 19:10:51,471 6513 ERROR openerp_test odoo.addons.pos_loyalty.tests.test_pos_loyalty: `     self.fail(lline)
2019-02-08 19:10:51,471 6513 ERROR openerp_test odoo.addons.pos_loyalty.tests.test_pos_loyalty: ` AssertionError: error tour test_pos_loyalty_acquire_points failed at step .o_main_content:has(.loader:hidden)
2019-02-08 19:10:51,472 6513 INFO openerp_test odoo.addons.pos_loyalty.tests.test_pos_loyalty: Ran 1 test in 21.185s
2019-02-08 19:10:51,472 6513 ERROR openerp_test odoo.addons.pos_loyalty.tests.test_pos_loyalty: FAILED
2019-02-08 19:10:51,473 6513 INFO openerp_test odoo.addons.pos_loyalty.tests.test_pos_loyalty:  (failures=1)
2019-02-08 19:10:51,473 6513 INFO openerp_test odoo.modules.module: odoo.addons.pos_loyalty.tests.test_pos_loyalty tested in 21.19s, 3000 queries
2019-02-08 19:10:51,473 6513 ERROR openerp_test odoo.modules.module: Module pos_loyalty: 1 failures, 0 errors

**Comment by chienandalu** [comment]
@rafaelbn There's an open issue here: https://github.com/OCA/pos/issues/309

**Pull request closed without merging**
