### PR TITLE
[17.0][ADD] pos_partner_vat_required: New module pos_partner_vat_required

### PR DESCRIPTION
**Pull request by peluko00**
The module put the vat field required on POS partner view.

cc https://github.com/APSL 161009
@miquelalzanillas @lbarry-apsl @javierobcn @mpascuall @BernatObrador @ppyczko please review

### CODE REVIEW

**Review by miquelalzanillas — APPROVED** [review]
Functionally tested. LGTM!

**Review by mpascuall — APPROVED** [review]
LGTM! Tested in runboat

**Review by BernatObrador — APPROVED** [review]
LGTM, tested in runboat + code review

**Review by ppyczko — APPROVED** [review]
LGTM!

**Comment by peluko00** [comment]
Hi @etobella , could you review please. Thanks!

**Review by etobella — APPROVED** [review]
It works as expected

/ocabot merge nobump

**Pull request merged**
