### PR TITLE
[MIG] pos_session_pay_invoice: Migration to 13.0

### PR DESCRIPTION
**Pull request by olgamarcocb**
#603 Superseded following the comments of the author

### CODE REVIEW

**Comment by etobella** [comment]
@acsonefho We have checked the original PR and there have been a lot of changes on the management of Point Of Sale, mainly on payments. However, we have a solution, I hope it will be here today or tomorrow :tada:

**Review by etobella — APPROVED** [review]
Tested locally

**Comment by etobella** [comment]
@acsonefho This is ready for review.

**Comment by aisopuro** [comment]
In case it helps with the review, this should be the "actual" diff between 12.0 and this migrated version: https://github.com/OCA/pos/compare/e464e61c1100ee9f33b45f5292334da4ca3e4708...tegin:13.0-mig-pos_session_pay_invoice

**Comment by dortunbo** [comment]
Hi,

While testing the module, I've noticed the following wrong behavior:

- Inside the same POS session, getting payment from two invoices, the invoice with the highest amount paid by Bank and the other paid by Cash. Once the session is closed, if you check the Invoice paid by Bank at Invoicing, two payments will appear: one from the invoice paid by Cash and the other from the invoice paid by Bank minus the amount of the invoice paid by Cash.

Apart from that, a suggestion, in terms of usability, would be to show the Partner field on the list of results when searching for more invoices / bills (Search More...).

I hope it helps.

**Comment by dortunbo** [comment]
@olgamarcocb Do you plan to finish the PR? 

Thanks,

**Comment by olgamarcocb** [comment]
@dortunbo I have tested it locally and it worked fine. I will test again in runbot in order to check it.

About the usability, I applied the change.

**Review by fshah-initos — COMMENTED** [review]
I have done functional tests and code reviews.
This module has errors as shown in the video.

https://user-images.githubusercontent.com/50449194/139677831-b32aefaf-8847-4c78-8d1e-e306f97293c0.mp4

**Comment by dsolanki-initos** [comment]
Hello, @olgamarcocb Can you resolve this issue as shown in the video.

**Comment by dsolanki-initos** [comment]
@olgamarcocb it would be nice you see this video and resolve this issue.

**Comment by etobella** [comment]
@dsolanki-initos which version of odoo are you using? the error seems related to your version, as it is complaining of the function `_get_rounded_amount` that you can find here: https://github.com/odoo/odoo/blob/13.0/addons/point_of_sale/models/pos_order.py#L348

So, not a module issue IMO

**Comment by etobella** [comment]
Checking the function, this was added on this commit odoo/odoo@d54a76d
this was added on 2020 when odoo 13.0 was already released. However, the problem is related to using an old odoo version from your side.

**Comment by dortunbo** [comment]
@dsolanki-initos I think @etobella is right because I am not facing the issue that it is shown on the video.

**Review by ivantodorovich — APPROVED** [review]

**Pull request merged**
