### PR TITLE
[12.0] pos_hr backporting

### PR DESCRIPTION
**Pull request by ygcarvalh**
## Description of the issue/feature this PR addresses:
This PR backports functionality that is present in version 13.0 but not in 12.0. It consists of allowing a Point of Sale login system from the registration of a PIN or a barcode for an employee registered in the system.

## Current behavior before PR:
The current form does not have this type of functionality and, once a POS session is opened, it opens directly on the screen.

## Desired behavior after PR is merged:
After the PR, when clicking to open a new POS session, it will open a login screen to be able to select the employee and a password - if any.

#### Suggestions are welcome to improve this PR in some way.

cc: @mileo
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by chienandalu — COMMENTED** [review]
Don't add Odoo's whole commit history. Just move your adaptations to make the backport work and respect proper copyright attributions

**Comment by ygcarvalh** [comment]
> Don't add Odoo's whole commit history. Just move your adaptations to make the backport work and respect proper copyright attributions

Oh, thanks. I didn't know that, I'll do it.

**Comment by ygcarvalh** [comment]
@chienandalu something like this?

**Comment by pedrobaeza** [comment]
@chienandalu please don't give contradictory advises. The commit history is very interesting, and I told him to respect it, only squashing translation commits. The only exception is when you extract a part of module, or the commit history is mixed with other things.

**Comment by pedrobaeza** [comment]
I'm seeing a potential problem with whole commit history, which is the CLA Bot (when working), as Odoo stuff haven't signed it. Let's do this:

- Put an initial commit under author `Odoo <info@odoo.com>` of the module as is from Odoo.
- Add a new commit with the needed changes for v12 with your authorship.

For reference, this comes from https://github.com/OCA/OCB/pull/1031

**Comment by ygcarvalh** [comment]
> I'm seeing a potential problem with whole commit history, which is the CLA Bot (when working), as Odoo stuff haven't signed it. Let's do this:
> 
> * Put an initial commit under author `Odoo <info@odoo.com>` of the module as is from Odoo.
> * Add a new commit with the needed changes for v12 with your authorship.
> 
> For reference, this comes from [OCA/OCB#1031](https://github.com/OCA/OCB/pull/1031)

Thank you very much for the advice, I will do it. It also took a doubt from me about how it works in this type of situation and it makes perfect sense.

**Pull request closed without merging**
