### PR TITLE
Make pos_customer_display odoo9 compatible

### PR DESCRIPTION
**Pull request by wamdam**
Hey, send me over whatever I have to sign (contributor agreement) and please merge this. This makes pos_customer_display odoo 9 compatible.
It is working for me.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Hi, @wamdam, thanks for the contribution. Please follow https://odoo-community.org/page/cla for sending the CLA.

**Comment by wamdam** [comment]
I sent it to "cla AT odoo-community.org" at the moment I created the pull request.

**Comment by pedrobaeza** [comment]
Thanks. I have just processed the CLA and next time you make a commit a message saying so will appear. Now you can wait for reviewers, or you can review other OCA/POS PRs and ask for a review here as payback.

**Review by alexis-via — APPROVED** [review]
Works great on Odoo 9 with my Bixolon LCD and pywebdriver. Great work ! Don't forget to update version number in **openerp**.py

**Comment by alexis-via** [comment]
I ported the module pos_customer_display to v10 starting from the code of this PR ; it was really easy. In v10, I removed the button "show total to customer", because I think that, since v9, it's not necessary any more: we display the total when you click on the "Payment" button. I'll do a PR for v10 soon.

**Review by pedrobaeza — APPROVED** [review]
Trusting in @alexis-via test + diff review, I approve.

**Pull request merged**
