### PR TITLE
[BACKPORT][13.0] pos_coupon from odoo 15.0

### PR DESCRIPTION
**Pull request by ivantodorovich**
This is a backport of `pos_coupon` module [found in odoo/odoo:15.0](https://github.com/odoo/odoo/tree/03641610c2b4a6b832ea87795fd21e1d7af10b59/addons/pos_coupon)

It's been adapted to work with `sale_coupon` module instead of the newly generic `coupon` module found in the latest version.

### CODE REVIEW

**Review by chienandalu — COMMENTED** [review]
Are there licencing issues backporting from odoo:master and not from a released version? Do you know it @pedrobaeza or @legalsylvain ?

**Comment by ivantodorovich** [comment]
It seems tests are failing in travis, possibly because an incompatibility with another module in this repo. I'm looking into it

**Comment by legalsylvain** [comment]
> Are there licencing issues backporting from odoo:master and not from a released version?

No. I don't see why. we can backport what we want ! The only things is to keep the same licence. (here, @ivantodorovich set LGPL, as the current master version, so it's OK for me).

**Comment by pedrobaeza** [comment]
Yes, 3 main things:

- Respect same license.
- Make an initial commit with the raw module attributing to Odoo (for example, commit author email info@odoo.com).
- Put a clause in the README about the lack of CLA
 
See https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#10backporting-odoo-modules for more details.

**Comment by chienandalu** [comment]
Thanks everyone. I was wondering what happens if Odoo decided to pull back this code to enterprise in the last minute

**Comment by pedrobaeza** [comment]
If it has been published once openly, then you can continue using that code forever. You can't backport improvements done in enterprise branch since the closure though, but you can improve it on your own.

**Comment by ivantodorovich** [comment]
Thanks everyone!

I've amended the first commit, to set `Odoo SA <info@odoo.com>` as author.
The other two items in @pedrobaeza 's list are already done :)

**Comment by ivantodorovich** [comment]
Travis error is because of https://github.com/OCA/pos/pull/640
Will rebase this after the other one is merged

**Comment by ivantodorovich** [comment]
So travis failed again, here's another PR to fix the issue: https://github.com/OCA/pos/pull/641, this time related to `pos_fix_search_limit`
Again I'll rebase this one after the fix is merged and hopefully it would be green :crossed_fingers:

**Comment by ivantodorovich** [comment]
Still red.. :sweat: 

This time `pos_empty_home` is affecting tours.. of course, as it completely removes the product list if no category is selected.
I've made a new PR here: https://github.com/OCA/pos/pull/642 to make it configurable and disabled by default on the demo pos.config: `point_of_sale.pos_config_main`.

Again, I'll rebase this one after the other one is merged and hopefully it'll be green afterwords :roll_eyes:

**Comment by ivantodorovich** [comment]
Travis is green :)

**Pull request closed without merging**
