### PR TITLE
[8.0][ADD] Autoreconcile invoiced orders in POS

### PR DESCRIPTION
**Pull request by jcarlosmontoya**
This module automatically reconcile invoiced orders in POS  when  close session

### CODE REVIEW

**Comment by rafaelbn** [comment]
Please check travis

```
+=======================================

|  Tests summary:

|---------------------------------------

| test_flake8                 FAIL

| test_pylint                 FAIL

+=======================================
```

**Comment by rafaelbn** [comment]
@jcarlosmontoya Which is the diference between this PR and this one https://github.com/OCA/pos/pull/27/files ? Thanks

**Comment by rafaelbn** [comment]
@jcarlosmontoya Which is the diference between this PR and this one https://github.com/OCA/pos/pull/27 ? Thanks

**Comment by jcarlosmontoya** [comment]
@rafaelbn, PR #27 works to create account move lines (after) , so  reconciles only paid orders, not invoiced orders, this PR works before to create account move lines.
Even from this module you could kill all birds with one shoot (paid and invoiced orders) 

This module was made to work separately with #27.

**Comment by rafaelbn** [comment]
So this PR is the same as @legalsylvain and @andrius-preimantas talked here https://github.com/OCA/pos/pull/27#issuecomment-143197131. Right?

**Comment by pedrobaeza** [comment]
CLA processed!, so no problem with that to continue the PR

**Comment by rafaelbn** [comment]
Hi @jcarlosmontoya , could you fix branch conflicts? I will test it. Thanks! 

cc @JGarcia-Panach

**Comment by rafaelbn** [comment]
Hi @jcarlosmontoya could you please rebase here in order to check and test it please? Thanks!

**Comment by damendieta** [comment]
Hi, Is this module still on development?, Do you plan to port it to v9?. Do you need help?.

Daniel.

**Comment by legalsylvain** [comment]
Hi @damendieta . Did you checked #27 module ?

Regards.

**Comment by libreec** [comment]
Hi, yes, I did, but I don't understand why there are this two PR still open, if this one is not going to continue in development, I think that it's better to close it.

Thanks a lot.

Daniel.

**Comment by legalsylvain** [comment]
pos_autoreconcile has been merged. did you tried it ?

https://github.com/OCA/pos/tree/8.0/pos_autoreconcile (V8.0)

regards.

**Comment by legalsylvain** [comment]
closing this PR as pos_autoreconcile has been merged.

**Pull request closed without merging**
