### PR TITLE
[14.0] pos_payment_change

### PR DESCRIPTION
**Pull request by fshah-initos**

### CODE REVIEW

**Review by dsolanki-initos — APPROVED** [review]
LGTM. Functional and Code review

**Comment by fshah-initos** [comment]
Hi @chienandalu It would be great if you could add reviews here

**Comment by fshah-initos** [comment]
It would be great if we get the reviews here

**Comment by fshah-initos** [comment]
@quentinDupont 
It would be nice if you can add reviews here.

**Comment by fshah-initos** [comment]
It would be nice if you can add reviews here.

**Comment by fshah-initos** [comment]
It would be nice if we can get the reviews here

**Comment by fshah-initos** [comment]
It will be nice if we can get the reviews here

**Review by ivantodorovich — APPROVED** [review]

**Pull request merged**
