### PR TITLE
[10.0] Migrate pos_customer_display

### PR DESCRIPTION
**Pull request by alexis-via**
I removed the button "Show total to customer" in the interface of the POS because, since v9, the new design of the interface makes it "natural" to show the total when the cashier presses the big "Payment" button (and, if he needs to continue to scan products, he can press "Back"). Si I also modified the JS code so that the total is displayed when the cashier presses the big "Payment" button.

I successfully tested this PR on my Odoo 10 with pywebdriver and my BCD-1100 LCD.

### CODE REVIEW

**Comment by alexis-via** [comment]
FYI, to port this module from 9 to 10, I used the new method "git format-patch" + "git am" method, as documented on https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0#experimental-procedure-that-works-with-merge-commits-and-can-be-restarted-in-case-of-conflicts

**Comment by rafaelbn** [comment]
Hi @alexis-via , could you please rebase in order to be sure all is OK after changes @lasley made yesterday? Also please could you add test to have a coverage acceptable? Thanks a lot

**Comment by alexis-via** [comment]
Rebased.

I have no idea how to add JS tests. It's above my technical skills in JS.

**Comment by alexis-via** [comment]
This code has been used in production since January 1st 2017 and is working very well. It's ready to merge.

**Comment by legalsylvain** [comment]
Hi, 
Well : 

* A full review of this kind of PR without the according hardware can not be done.
* waiting for 2 reviewers will take a while or will not occur.

Propose to realize optimistic merge. 

@alexis-via , could you just remove commented "console.log" line please ? (l 108)

regards.

**Comment by legalsylvain** [comment]
ping @alexis-via : could you remove this line. 
https://github.com/akretion/pos/blob/10-mig-pos_customer_display/pos_customer_display/static/src/js/customer_display.js#L108
merging after that.

kind regards.

**Comment by Ralfefernandes** [comment]
I have a problem.. right now, my pole display can read the data from odoo(odoo 10), but the problem is that, he is only showing the price without tax. But what i want is to show the total price including the tax price.  And if i scan the second products, the price doesn't change. What do i have to do?

**Comment by legalsylvain** [comment]
Thanks  @alexis-via. Merging.

@ Ralfefernandes : I guess that you're problem come from tax configuration. (tax include / exclude settings).

**Pull request merged**
