### PR TITLE
16.0 mig pos default partner

### PR DESCRIPTION
**Pull request by alv97**
Migration of what was implemented for 14.0. No extra modifications were made.

Related: https://github.com/OCA/pos/issues/849

### CODE REVIEW

**Comment by alv97** [comment]
I have added my corporate account to my personal github account, which is where I sign the CLA, so the above @oca-clabot  message should be resolved.

**Review by PierrickBrun — APPROVED** [review]
code review LGTM

**Comment by alv97** [comment]
Some news about this?

**Review by ivantodorovich — APPROVED** [review]

**Comment by HaraldPanten** [comment]
Hi @ivantodorovich @pedrobaeza it seems that some of the commit history for this module has been lost in the migration process.

How could that be solved?

For example --> https://github.com/OCA/pos/commit/f33cdab54c35416ba6673007857c92510d8fe8e8

We were planning to make the migration to V15 and we realized that some work is missing here...

**Pull request merged**
