### PR TITLE
[IMP] Add German Language

### PR DESCRIPTION
**Pull request by mncoon**
Add german PO-file for the Customer Display.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1: from technical point of view.

**Comment by mncoon** [comment]
I have signed the CLA last year. Is this necessary every year?

**Comment by legalsylvain** [comment]
- Yes, you firmed the CLA, but your github login was unknown. I updated the OCA database with your Github login. It will be OK for your next PRs. CC: @gurneyalex 
- :+1: Thanks for your PR.

**Comment by gurneyalex** [comment]
thanks @legalsylvain for the CLA handling.

**Pull request merged**
