### PR TITLE
[16.0] [MIG] pos_reset_search

### PR DESCRIPTION
**Pull request by victor-champonnois**
Currently not working. When searching and then clicking on a product, an error is raised :
```
TypeError: ProductScreenChildren[key].el is undefined
    _clickProduct@http://localhost:8012/web/assets/debug/point_of_sale.assets.js:45187:25 (/pos_reset_search/static/src/js/ProductScreen.js:13)
    __trigger@http://localhost:8012/web/assets/debug/web.assets_common.js:22576:21 (/web/static/src/legacy/legacy_component.js:89)
    trigger@http://localhost:8012/web/assets/debug/web.assets_common.js:22560:14 (/web/static/src/legacy/legacy_component.js:73)
    template/hdlr2<@http://localhost:8012/web/assets/debug/web.assets_common.js line 21902 > Function:14:25 (/web/static/lib/owl/owl.js:5508)
    mainEventHandler@http://localhost:8012/web/assets/debug/web.assets_common.js:22169:25 (/web/static/lib/owl/owl.js:5775)
    listener@http://localhost:8012/web/assets/debug/web.assets_common.js:16792:20 (/web/static/lib/owl/owl.js:398)

```
So far, I don't understand the problem. Help would be very welcomed :)

### CODE REVIEW

**Comment by carmenbianca** [comment]
@victor-champonnois I fixed this PR for ya.

**Review by carmenbianca — APPROVED** [review]

**Comment by robinkeunen** [comment]
@victor-champonnois Can you undraft this PR ? 
@legalsylvain this is waiting a Christmas review 🥳

**Review by legalsylvain — APPROVED** [review]

**Comment by chienandalu** [comment]
:santa: 

/ocabot merge nobump

**Pull request merged**
