### PR TITLE
[13.0][FIX]pos_order_mgmt: Fix bug when restore payment lines from a done o…

### LINKED ISSUE #732: [13.0]pos_order_mgmt: Reprint ticket doesent print original paymentlines
## Module
pos_order_mgmt

## Describe the bug
When try to reprint a ticket, i get the ticket without the original paymentlines.

## To Reproduce
Use the reprint ticket button on the order history screen and the payment lines is not printed

**Expected behavior**
A exact copy of the original ticket

**Additional context**
The funtion _prepare_order_from_order_data, try to match the paymentlines with the cashregisters.
```js
 if (["print"].indexOf(action) !== -1) {
                var paymentLines = order_data.statement_ids || [];
                _.each(paymentLines, function(paymentLine) {
                    var line = paymentLine;
                    // In case of local data
                    if (line.length === 3) {
                        line = line[2];
                    }
                    _.each(self.pos.cashregisters, function(cashregister) {
                        if (cashregister.journal.id === line.journal_id) {
                            if (line.amount > 0) {
                                // If it is not change
                                order.add_paymentline(cashregister);
                                order.selected_paymentline.set_amount(line.amount);
                            }
                        }
                    });
                });
            }
```

but `self.pos.cashregisters` is obsolete, no cashregisters in pos model.

### PR DESCRIPTION
**Pull request by javierjcf**
…rder. Fixes #732

### CODE REVIEW

**Comment by legalsylvain** [comment]
Thanks @javierjcf for the patch !

@dalonsod  could you take a look on that PR, as you made the port of the module to 13 ? (https://github.com/OCA/pos/pull/584)

regards.

**Comment by dalonsod** [comment]
Hello @javierjcf , thanks for the contribution!

Locally tested, works as expected. Please squash commits and execute pre-commit stuff.

**Comment by javierjcf** [comment]
Hi @dalonsod 
I did squash and the pre-commit

**Comment by chienandalu** [comment]
Are you sure? It's still failing

**Comment by dalonsod** [comment]
Hello @javierjcf if you install `pre-commit` python library and execute `pre-commit run -a` that command will do that work

**Comment by javierjcf** [comment]
Thanks @dalonsod , it's well done right now i think

My problem was not commiting changes that pre-commit did

**Review by dalonsod — APPROVED** [review]

**Review by chienandalu — APPROVED** [review]

**Comment by chienandalu** [comment]
Thanks @javierjcf :)

**Pull request merged**
