### PR TITLE
FIX pos change payment bad rounding compute

### PR DESCRIPTION
**Pull request by flotho**
Use currency and monetary so that rounding will be done by the ORM*

### CODE REVIEW

**Comment by flotho** [comment]
ping @legalsylvain

**Review by legalsylvain — APPROVED** [review]
Thanks for the patch !
Could you fix travis ? (Just lint problem)
Kind regards.

**Comment by legalsylvain** [comment]
still failing ;-) https://travis-ci.org/github/OCA/pos/jobs/713467971#L307

**Comment by flotho** [comment]
Hi @legalsylvain ,

Sorry for this newbie question, could please remind me where to find magical command for solving pep issue thanks to the oca lib?
Thanks

**Comment by legalsylvain** [comment]
hi @flotho. 
- when migrate module, you can use this [tool](https://github.com/grap/odoo-module-migrator/).
- since V13, precommit will try to fix automatically bad syntaxed code.

but for that case, I think you have to fix it manually.

kind regards.

**Comment by legalsylvain** [comment]
hi @flotho, do you need some help on that point ?

**Comment by flotho** [comment]
hi @legalsylvain ,

Totally need your help, I'm both overbooked and a newbie on this tool, that make two bad reasons to not succeed in doing correct stuff.

**Comment by legalsylvain** [comment]
Hi @flotho : 
you have to click on "detail"
image
Then the red line
image
then, in the end check the test(s) that is / are failing : 
image

In your case you have to fix the following lines: 
image

 
let me now if you still have some problem to fix flake8 issue.

thanks !

**Comment by flotho** [comment]
Hi @legalsylvain , 

This one I already got, my question is more about the command odoo-pylint to solve automatically this kind of issue.
Regards

**Comment by legalsylvain** [comment]
Hi @flotho 

pylint is green. log displays only non blocking warnings. You can ignore them.
Not sure but, I think that there warnings will be fixed in V13, when migrating with new precommit OCA mechanism.

**Comment by flotho** [comment]
@legalsylvain , my bad, I was mixing pylint and flake because of the name of the build (facepalm)
I'll have a look to this

**Comment by legalsylvain** [comment]
thanks.

/ocabot merge patch

**Pull request merged**
