### PR TITLE
10.0 mig pos remove pos category

### PR DESCRIPTION
**Pull request by mourad-ehm**

### CODE REVIEW

**Comment by legalsylvain** [comment]
:+1:. LGTM. Code review, No test. thanks for porting this module.

**Comment by mourad-ehm** [comment]
Thanks @legalsylvain for review. 
There is yet JS error:
warning: Some modules could not be started 
Missing dependencies:    Array [ "point_of_sale.models", "point_of_sale.screens" ] 
Non loaded modules:      Array [ "pos_remove_pos_category.remove_pos_…" ] 
Debug:                   Object { pos_remove_pos_category.remove_pos_category: Object }  web.assets_common.js:2994:817

**Comment by legalsylvain** [comment]
@mourad-ehm. Is it still WIP ?

**Comment by mourad-ehm** [comment]
Hi @legalsylvain, I deleted wip comment. @sylvainc has fixed Js bug

**Review by legalsylvain — APPROVED** [review]
Thanks. Code review / no test.

**Comment by mourad-ehm** [comment]
Hi @legalsylvain, could you merge this PR please ?

**Comment by Cedric-Pigeon** [comment]
@legalsylvain Why did you merge it with only one approval (yours) ? This module is not usable on an existing database because of the monkey patch.

**Comment by legalsylvain** [comment]
Hi @Cedric-Pigeon. Sorry, I merged too quickly with only one approval. 

About your point, I don't understand why it doesn't work because of the monkey patch ? could you explain ? this is the same behaviour as the module in 8.0.

Kind regards.

**Comment by Cedric-Pigeon** [comment]
The monkey patch doesn't trigger. In V10.0 you are not supposed to work like this. You must inherit from BaseModel. I am preparing a new PR to fix

**Comment by legalsylvain** [comment]
Thanks a lot. I did'nt catch it.
Please ping me and ping @sylvainc + @mourad-ehm + @simahawk , when you'll do your PR.

kind regards.

**Comment by Cedric-Pigeon** [comment]
See https://github.com/OCA/pos/pull/182

**Pull request merged**
