### PR TITLE
[13.0] [mig] pos_fix_search_limit

### PR DESCRIPTION
**Pull request by dsolanki-initos**

### CODE REVIEW

**Comment by dsolanki-initos** [comment]
@legalsylvain  can you please review the PR?

**Comment by legalsylvain** [comment]
Hi. I think that @hpar original author and @cvinh (migration to 11.0), @wpichler (migration to 12.0) could have a more interesting point of view regarding this migration.

**Comment by dsolanki-initos** [comment]
@wpichler It would be great if you could add reviews here.

**Review by fshah-initos — APPROVED** [review]
LGTM. Code and functional review.

**Pull request merged**
