### PR TITLE
[MIG] pos_product_template: Migration to 11.0

### PR DESCRIPTION
**Pull request by imjaypatel**
[MIG] pos_product_template: Migration to 11.0

### CODE REVIEW

**Comment by pedrobaeza** [comment]
There's already another PR in progress in #284. Can you review that one instead?

**Comment by imjaypatel** [comment]
> There's already another PR in progress in #284. Can you review that one instead?

Yes I checked @284 pull request are in queue since Aug 2018. How long time it will take to merge this pull request ?

Thanks

**Comment by pedrobaeza** [comment]
While not reviewed, it will be there for ever. Please review it

**Comment by imjaypatel** [comment]
> While not reviewed, it will be there for ever. Please review it

I will bring branch in my local and check code and functionality. if it is working fine then next what should i do in Github?

Thanks

**Comment by pedrobaeza** [comment]
You can rebuild Runbot for trying there if you want. Check https://odoo-community.org/page/review

**Pull request closed without merging**
