### PR TITLE
[FIX][8.0] travis: Update travis file to new standard

### PR DESCRIPTION
**Pull request by lasley**
* Add new matrix
* Add transifex support
* Switch coveralls to travis_after_tests_success
* Move pip requirements to requirements.txt

Related #140  #139

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can you please protect the 2 imports for having a green build?

**Comment by lasley** [comment]
Done

**Comment by pedrobaeza** [comment]
Uhm, you have opened the Pandora's box, hehe. Modifying files in that module has activated other checks that also fails.

**Comment by lasley** [comment]
Damn well that escalated quickly. I'll put this on my list of things to look at, seems theres missing readmes and stuff that'll take a bit more thought.

**Comment by rafaelbn** [comment]
Please travis masters @Yajo @pedrobaeza what should we do with this PR?

**Comment by yajo** [comment]
I think @moylop260 can help more than me here.

**Comment by moylop260** [comment]
Seems like as a travis internal error.
Maybe a new commit to run a new build (I don't have permission to rebuild it)
Fixing conflicts too could help.

**Comment by pedrobaeza** [comment]
I have rebased and fix this, so I fast-track it.

**Pull request merged**
