### PR TITLE
Add OCA as author of OCA addons

### PR DESCRIPTION
**Pull request by gurneyalex**
In order to get visibility on https://www.odoo.com/apps the OCA board has
decided to add the OCA as author of all the addons maintained as part of the
association.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by legalsylvain** [comment]
:question: Excuse but I don't see why OCA is the 'author' of all the modules.
Can you send a link with discussion about that ?
Regards.

**Comment by gurneyalex** [comment]
@legalsylvain this was a decision of the board. The goal is to let the OCA gain visibility, and one way to achieve this is through https://www.odoo.com/apps/contributors/modules/

We asked the editor to add a field to let people find OCA addons easily and we got a negative answer, so we decided to add the OCA as author in the addons metadata (of course without removing the original author, nor changing the website field). There will be other PR to update the description field of the addons to include the OCA template.

**Comment by legalsylvain** [comment]
not very clear for me but if we don't have other choice...

**Comment by gurneyalex** [comment]
@legalsylvain the goal is not to alienate our contributors, and I realize we should have communicated before doing the move. I apologize for not doing so.

**Comment by legalsylvain** [comment]
No problem, I understand the problem, and this appears to be a "non-perfect-but-ok solution'
But yes, more communication from OCA Board (main decision) should be great.
Anyway, thanks for your work.
Regards.

**Pull request merged**
