### PR TITLE
[FIX] pos_picking_delayed: ensure test correctness

### PR DESCRIPTION
**Pull request by chienandalu**
https://github.com/OCA/pos/pull/405 was prematurely merged :smile: . This one can be fast-tracked once CI's pass

cc @Tecnativa

### CODE REVIEW

**Comment by legalsylvain** [comment]
Hi don't understand the reason of this patch. Could you point the error ?
Travis is green, and all seems OK.

**Comment by chienandalu** [comment]
> Could you point the error ?

Again? :sweat_smile: The reason is to ensure tests correctness despite default currency. Otherwise, there is an exception due to the default pricelists default currency wich could be different. So:

- A pricelist must be created on the test
- Such pricelist must be assigned to de pos.config used.
- If we just copy the pos.config, the exception raises.
- So in this patch, we ensure the copied pos.config has no such issues.

**Review by pedrobaeza — APPROVED** [review]
I don't have clear why the previous code didn't work, but this is the same harmless IMO, so go ahead.

**Comment by chienandalu** [comment]
Because the of the copy()

**Comment by chienandalu** [comment]
@legalsylvain This is the exact error. And it's due to the reasons I pointed out.
```
ValidationError: ('All available pricelists must be in the same currency as the company or as the Sales Journal set on this point of sale if you use the Accounting application.', None)
```
In this last patch I respect your implementation of the test but just preventing this fail.

Let's merge it and go on with other stuff :wink:

**Comment by legalsylvain** [comment]
OK. On that point, not sure to have understood finally ;-), as Travis branch is green. (https://travis-ci.org/OCA/pos/branches) But no problem at all to merge, and let's go talking about more interesting point.

Thanks for the patch !

/ocabot merge

**Pull request merged**
