### PR TITLE
[14.0] [mig] pos_partner_firstname

### PR DESCRIPTION
**Pull request by dsolanki-initos**

### CODE REVIEW

**Review by francesco-ooops — CHANGES_REQUESTED** [review]
When editing company name > save, changes are not saved
Also when editing company name, fields "first name" and "last name" become visible

REQUIRED BEHAVIOR

Name of company should be edited and saved in "name" field
Fields "first name" and "last name" should not be visible if flag "company" is active

[video](https://recordit.co/hmYE0iAzXv)

**Comment by dsolanki-initos** [comment]
@francesco-ooops 
Thank You for the review!
I've done some change to work as required. Can you please recheck?

**Review by francesco-ooops — CHANGES_REQUESTED** [review]
1) edit company name > deselect flag "company" and select again > name is not editable

[VIDEO](https://recordit.co/pxJ6q6a37k)

2) Select customer > click on customer > edit > enter new name > save > click "discard"

CURRENT BEHAVIOR

Name of partner is changed, but in main POS interface old name is still displayed (not updated)

[VIDEO](https://recordit.co/aA9sfL30o4)

3) Select customer > edit data > click "Set customer"

CURRENT BEHAVIOR

Edited data is lost when pressing the suggested button ("Set customer")

[VIDEO](https://recordit.co/jsBi01sADi)

REQUIRED BEHAVIOR

This issue was prevented in v.12 by not displaying button "Set customer" until either "Save" or "Discard" was pressed, maybe this option could be adopted in this version too

---

MINOR (this behavior was also present in v.12)

Every time "company" is clicked, a space is added in name field

[VIDEO](https://recordit.co/HRV56ScnR7)

**Review by iwkse — CHANGES_REQUESTED** [review]
1. click on customer > select customer > set customer > click on customer > edit same customer > enter new name > save > click "discard"

CURRENT BEHAVIOR
Name of partner is changed, but in main POS interface old name is still displayed (not updated)
[VIDEO](https://recordit.co/aA9sfL30o4)

Also there's issues on tests related to other modules.

**Comment by francesco-ooops** [comment]
@dsolanki-initos runbot/boat is not up so can't do functional review

**Comment by iwkse** [comment]
@dsolanki-initos please could you fix the runboat? Would be really appreciated, thank you

**Review by iwkse — APPROVED** [review]
LGTM
There's an error in tests, did you try to rebase?

**Review by francesco-ooops — APPROVED** [review]
@dsolanki-initos functional review ok

**Comment by francesco-ooops** [comment]
> LGTM There's an error in tests, did you try to rebase?

@dsolanki-initos could you please?

**Comment by francesco-ooops** [comment]
@OCA/pos-maintainers I see travis here is failing due to an issue with pos_order_return tests

I've noticed also PRs #758 #756 and #768 are failing for the same reason, could you advise how to solve it?

Thanks!

**Comment by robyf70** [comment]
@legalsylvain Do you know why I cannot merge the PR since I'm the maintainer?

**Comment by legalsylvain** [comment]
Ocabot only allow to merge patch from maintainers. (= ob existing modules)
This module doesnt exist in v14.

Note : i think we should fix travis before merging.

**Comment by robyf70** [comment]
> Ocabot only allow to merge patch from maintainers. (= ob existing modules) This module doesnt exist in v14.
> 
> Note : i think we should fix travis before merging.

This means ``pos_order_return`` right?

**Comment by francesco-ooops** [comment]
> @OCA/pos-maintainers I see travis here is failing due to an issue with pos_order_return tests
> 
> I've noticed also PRs #758 #756 and #768 are failing for the same reason, could you advise how to solve it?
> 
> Thanks!

@robyf70 yup, it's blocking several PRs

**Comment by robyf70** [comment]
@dsolanki-initos Can you please rebase and push force since @legalsylvain has disabled the broken test on ``pos_order_return``?

**Comment by francesco-ooops** [comment]
@legalsylvain @robyf70 haven't received a reply from @dsolanki-initos about this module in the last month either here or by email, probably opening a new PR for migration is the easiest solution

**Comment by robyf70** [comment]
> @legalsylvain @robyf70 haven't received a reply from @dsolanki-initos about this module in the last month either here or by email, probably opening a new PR for migration is the easiest solution

I will do now

**Comment by robyf70** [comment]
> > @legalsylvain @robyf70 haven't received a reply from @dsolanki-initos about this module in the last month either here or by email, probably opening a new PR for migration is the easiest solution
> 
> I will do now

it's here #775

**Pull request closed without merging**
