### PR TITLE
[FIX] import and error in product code

### PR DESCRIPTION
**Pull request by legalsylvain**
supersed : https://github.com/OCA/pos/pull/165.

(the old PR was in the bad repository)

CC : @pedrobaeza, @invitu

### CODE REVIEW

**Review by NL66278 — APPROVED** [review]
I made similar (but more extensive) changes in this PR: https://github.com/OCA/pos/pull/167/files. In my PR I also standardized the directory structure. If you agree with my changes, I can rebase my PR on yours and add it to your PR. Or you can close this PR in favour of mine. If you do not agree, I approve this PR anyway, so we can get ahead with this important fix.

**Comment by legalsylvain** [comment]
@NL66278 you let the field on template, but I think it should be set on product. Don't you think ? 
Otherwise, no problem to close my PR, and keep yours.

regards.

**Comment by NL66278** [comment]
@legalsylvain Looking into it, it probably is better to set the field on the product. I changed my PR accordingly.

**Comment by legalsylvain** [comment]
supersed by https://github.com/OCA/pos/pull/167.
closing.

**Pull request closed without merging**
