### PR TITLE
[16.0][MIG] pos_picking_delayed

### PR DESCRIPTION
**Pull request by em230418**
Commits are from this PR https://github.com/OCA/pos/pull/1213

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]
Thanks a lot for your contribution, @em230418 !

Diff review, LGTM !

/ocabot migration pos_picking_delayed

**Review by ivantodorovich — APPROVED** [review]

**Comment by em230418** [comment]
Just added tick on "Allow edits by maintainers" in this PR. Probably it is the reason why it says "permission denined"

**Pull request merged**
