### PR TITLE
[ADD][14.0] pos_kiosk: self-service kiosks

### PR DESCRIPTION
**Pull request by ygcarvalh**
This module represents a comprehensive remake of the Point of Sale frontend, with a focus on UX of a self-service terminal while retaining the pos business logic. 

The core idea is to create a seamless extension of the existing `point_of_sale` module, enabling the future incorporation of additional customization modules.

In its current iteration, the primary modification involves redirecting the `controller` to a new URL, facilitating a specialized self-service experience. 

This strategic adjustment ensures that no disruptions occur within the Point of Sale system, while the existing business logic remains intact. Furthermore, this enhancement introduces new assets responsible for importing JavaScript files, selectively loading essential components to facilitate the process. Notably, this evolution refrains from altering any of the pre-existing developed screens.

This module crafts an entirely new user experience, tailored to enable the use of the point of sale system in self-service terminals/kiosks. 

This new interface retains the foundational models and business logic of the core module, focusing solely on remaking the user journey for simplified self-service interactions.

In certain instances, the introduction of supplementary modules may be necessary to incorporate new functionalities into the user interface.  These new modules could reuse existing components only defining it again in the new kiosk interface.

Moreover, the implementation introduces Tailwind CSS to streamline frontend customization. This innovation serves a dual purpose: consolidating the number of utilized .css files and simplifying the entire customization procedure.

Displayed below are a series of prototype images guiding the module's developmental trajectory.

image

image

image

image

image

It is important to acknowledge this work still in progress, susceptible to further refinement, including code implementation and related elements.

### CODE REVIEW

**Comment by mileo** [comment]
Some issues with responsiveness that should be on your radar. 

But we have a good start, congratulations.

image

image

**Comment by chienandalu** [comment]
Very cool contribution :slightly_smiling_face: :+1:

**Comment by mileo** [comment]
Nice!

https://github.com/OCA/pos/assets/1975978/002af57d-b174-4387-8db1-871782b3541a

**Comment by mileo** [comment]
[Screencast 2023-08-23 13:44:36.webm](https://github.com/OCA/pos/assets/1975978/c82d2218-feb1-4d5a-9024-17db799c7c8f)

**Comment by elvise** [comment]
@ygcarvalh woow!
great pr, let me know when is ready for testing

**Comment by ygcarvalh** [comment]
Hi, @elvise 

Sorry for the delay, it ended up taking me longer than expected with some corrections and based on the responsiveness of the elements.

If you want to test it, the only thing missing are some settings related to the POS part for Self-Service Mode, but it is extremely intuitive.

**Pull request closed without merging**
