### PR TITLE
[12.0][ADD] pos_payment_change

### PR DESCRIPTION
**Pull request by legalsylvain**
Propose new module pos_payment_change for Odoo 12.0

This module allows to change payments of a pos.order, once paid but before the session is closed (and the account moves generated).
This is usefull in the case the cashier made a mistake, and can fix it immediately, or during the close of the session, when he realize that there is too much money in a journal, and there's not enough money in another, to avoid to generate bad accounting data.

For that purpose, it adds a button on pos order form

pos_order_form

a wizard so appears, that will ask the new amount(s) for the new journal(s)

pos_payment_change_wizard_form

Two policy are available (setting on ``pos.config``): 
* Refund and Resale : this will create a refund, and then create a new order with the correct payment. This method is the default one, and is compatible with certification module. (In a certification context, like in France, orders can not be altered).
* Update Payments : statement lines will be changed.

pos_config_form

#GRAPOCA

### CODE REVIEW

**Comment by tonygalmiche** [comment]
With rubot, I got this error when trying to change the payment
```

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/models.py", line 4741, in ensure_one
    _id, = self._ids
ValueError: not enough values to unpack (expected 1, got 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/.repo_requirements/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/.repo_requirements/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/.repo_requirements/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/.repo_requirements/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/OCB-12.0/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/OCB-12.0/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/build/OCA/pos/pos_payment_change/wizards/pos_payment_change_wizard.py", line 65, in button_change_payment
    order_ids = order.change_payment(new_payments)
  File "/home/odoo/build/OCA/pos/pos_payment_change/models/pos_order.py", line 54, in change_payment
    refund_order.action_pos_order_paid()
  File "/home/odoo/build/OCA/pos/pos_order_return/models/pos_order.py", line 99, in action_pos_order_paid
    res = super(PosOrder, self).action_pos_order_paid()
  File "/home/odoo/OCB-12.0/addons/point_of_sale/models/pos_order.py", line 688, in action_pos_order_paid
    return self.create_picking()
  File "/home/odoo/build/OCA/pos/pos_picking_delayed/models/pos_order.py", line 34, in create_picking
    res = super(PosOrder, orders).create_picking()
  File "/home/odoo/build/OCA/pos/pos_order_return/models/pos_order.py", line 132, in create_picking
    res = wizard.create_returns()
  File "/home/odoo/OCB-12.0/addons/stock/wizard/stock_picking_return.py", line 153, in create_returns
    new_picking_id, pick_type_id = wizard._create_returns()
  File "/home/odoo/OCB-12.0/addons/stock_account/models/stock.py", line 740, in _create_returns
    new_picking_id, pick_type_id = super(StockReturnPicking, self)._create_returns()
  File "/home/odoo/OCB-12.0/addons/stock/wizard/stock_picking_return.py", line 118, in _create_returns
    'location_dest_id': self.location_id.id})
  File "/.repo_requirements/odoo/odoo/models.py", line 4313, in copy
    self.ensure_one()
  File "/.repo_requirements/odoo/odoo/models.py", line 4744, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: stock.picking()
```

**Comment by legalsylvain** [comment]
> With rubot, I got this error when trying to change the payment

@tonygalmiche It seems that there is some incompatibility with the module ``pos_order_return``. I'll investigate. Thanks for your review.

**Comment by tonygalmiche** [comment]
@legalsylvain it's ok on my computer

**Comment by legalsylvain** [comment]
@tonygalmiche : 
> With rubot, I got this error when trying to change the payment

1) regarding the error, it is due in fact to the incompatibility between ``pos_order_return`` and ``pos_picking_delayed``. This should be fixed by : https://github.com/OCA/pos/pull/481

> @legalsylvain it's ok on my computer

2) is it an approval ? 

thanks !

**Review by tonygalmiche — COMMENTED** [review]
@legalsylvain, 
OK for incompatibility between pos_order_return and pos_picking_delayed
It works on my personal computer. It's OK
I also looked at the code. It is OK for me
However, the README.rst is empty
Thank you for this new module

**Comment by legalsylvain** [comment]
>  However, the README.rst is empty

The readme.rst is automatically generated when ocabot is merging, using [this tools](https://github.com/OCA/maintainer-tools/#readme-generator). No need to propose it, if readme folder is present.

**Review by tonygalmiche — APPROVED** [review]
ok, i didn't know. Thank you

**Review by chienandalu — APPROVED** [review]
Great! Very useful :) Tested on runbot and code review :+1:

**Comment by legalsylvain** [comment]
Thanks @chienandalu and @tonygalmiche for your review.
I improved a little bit this PR, with the [last commit](https://github.com/OCA/pos/pull/480/commits/9853980c2aa0b961b653c8b0c45678ff8fdbd36c) : 
- I use default in copy() function, to have the original pos reference in the resold order.
- I added a text in the pos order notes, to know the history.

image

kind regards.

**Comment by legalsylvain** [comment]
Hi. Could you let a little bit this PR open ? I'm waiting for the review of a customer. thanks !

**Comment by chienandalu** [comment]
Sure

**Comment by flotho** [comment]
Hi @legalsylvain , do you need additional review ?

Regards

**Comment by legalsylvain** [comment]
Yes, it seems that there is a problem during the close of the session. I have to investigate.

**Comment by flotho** [comment]
Ok, your latest fix is not solving this issue. I'll try it too

**Review by flotho — APPROVED** [review]
tested successfully in production with the refund strategy in france.
LGTM

great job @legalsylvain

**Review by flotho — APPROVED** [review]

**Comment by legalsylvain** [comment]
Thanks !

/ocabot merge patch

**Pull request merged**
