### PR TITLE
[14.0][ADD] pos debranding module

### PR DESCRIPTION
**Pull request by ilyasProgrammer**

### CODE REVIEW

**Review by legalsylvain — CHANGES_REQUESTED** [review]
Hi @ilyasProgrammer.

thanks a lot for sharing this module.

AFAIK, there is a specific repository for all the unbranding stuff here : https://github.com/OCA/server-brand

I think that it should be better put in that repo.

what do you think ?

**Comment by ilyasProgrammer** [comment]
> 

Hello. Well it's related both debranding and POS. So not sure where to push it. I can create PR to server-brand if you think it's fits better there.

**Comment by legalsylvain** [comment]
> Hello. Well it's related both debranding and POS. So not sure where to push it. I can create PR to server-brand if you think it's fits better there.

yes, I think it's fits better in server-brand.

**Comment by ilyasProgrammer** [comment]
> > Hello. Well it's related both debranding and POS. So not sure where to push it. I can create PR to server-brand if you think it's fits better there.
> 
> yes, I think it's fits better in server-brand.

ok

**Pull request closed without merging**
