### PR TITLE
[13.0][MIG] pos_report_session_summary: Migration to 13.0

### PR DESCRIPTION
**Pull request by AntoniRomera**

### CODE REVIEW

**Review by FernandoRomera — APPROVED** [review]

**Comment by AntoniRomera** [comment]
@OCA/pos-maintainers Can someone check this module? I think it has no complexity to migrate.

**Review by MRomeera — APPROVED** [review]

**Review by ivantodorovich — APPROVED** [review]

**Comment by AntoniRomera** [comment]
@OCA/pos-maintainers Can someone check why is the merge stuck?

**Pull request merged**
