### PR TITLE
[17.0][MIG] pos_partner_birthdate: Migration to 17.0

### PR DESCRIPTION
**Pull request by rousemilano**
@pedrobaeza Buenas noches, por favor, quisiera el review tecnico, de este módulo que migre. Muchas gracias,

### CODE REVIEW

**Comment by legalsylvain** [comment]
Hi @rousemilano. Thanks for your contribution. 
At the first sight it looks like you didn't use correct git command to preserve git history. Could you take a look on that documentation ? https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0

thanks !

**Review by chienandalu — CHANGES_REQUESTED** [review]
You will need this: https://github.com/OCA/pos/pull/1072 (you can review the PR)

**Comment by rousemilano** [comment]
@chienandalu Hi, make other changes, but they need to enable the 17.0 branch to the "partner-contact" repository to be able to upload the missing module.

**Comment by chienandalu** [comment]
But you didn't follow the migration guidelines. Simply follow the script in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0

(you can save your module in another folder and paste it back after doing the initial migration tasks

**Comment by etobella** [comment]
@rousemilano will you follow @chienandalu comments?

**Comment by etobella** [comment]
Superseeded by #1104

**Comment by etobella** [comment]
It was working, but we needed to restore all the previous logic. Also, I made some changes to have the same approach we had on the current pos format. I will add yourself as co-author on my commit

**Pull request closed without merging**
