### PR TITLE
[11.0][ADD] pos_disable_lot_input: New module

### PR DESCRIPTION
**Pull request by chienandalu**
This module allows to prevent the manual input of lots in the PoS fronted.

This module is better used in combination with
`stock_pack_operation_auto_fill`, wich allows to autoassign lots to lines and
fill quantities based on stock policies. Some workflow tips provided below.

cc @Tecnaitva

### CODE REVIEW

**Comment by pedrobaeza** [comment]
What happens if you don't have the other module installed? Picking operations are correctly completed?

**Comment by chienandalu** [comment]
> What happens if you don't have the other module installed? Picking operations are correctly completed?

No, the lots should entered on every picking that would need it.

**Comment by pedrobaeza** [comment]
Then I see an inconsistency...

**Comment by chienandalu** [comment]
I wanted to keep the feature as generic as possible, as maybe other users want to implement a different type of automatation

**Comment by pedrobaeza** [comment]
Talked directly and module will be redirected to `pos_lot_auto_assign`

**Comment by chienandalu** [comment]
Closing this as the full workflow can be achieved setting off "Use Existing Lots/Serial Numbers" in PoS related picking type and setting the proper removal strategy for each location/product category.

Sorry about the noise

**Comment by MeetKD** [comment]
@chienandalu @rafaelbn @pedrobaeza It would be great if you can share link of pos_lot_auto_assign module.

I have set the  Use Existing Lots/Serial Numbers for pos related picking type but it will still ask to enter Lot/Serial Number in pos front end.

**Comment by chienandalu** [comment]
@MeetKD You have to set it off (https://github.com/odoo/odoo/blob/12.0/addons/point_of_sale/static/src/js/models.js#L1402)

**Comment by MeetKD** [comment]
@chienandalu thank you for the reference :+1:

**Pull request closed without merging**
