### PR TITLE
[15.0][MIG]pos_product_display_default_code

### PR DESCRIPTION
**Pull request by manuelregidor**
Standard migration

### CODE REVIEW

**Comment by manuelregidor** [comment]
@HaraldPanten @ValentinVinagre

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Review by HaraldPanten — APPROVED** [review]

**Comment by HaraldPanten** [comment]
@legalsylvain it's working fine.

**Comment by legalsylvain** [comment]
thanks for your contribution. 
No review.
/ocabot merge patch

**Comment by legalsylvain** [comment]
@manuelregidor could you rebase ? 
thanks !

**Comment by HaraldPanten** [comment]
@pedrobaeza @legalsylvain We should update the copier template here as well, right?

@manuelregidor

**Comment by pedrobaeza** [comment]
Yes

**Comment by manuelregidor** [comment]
@HaraldPanten @pedrobaeza The copier has been updated in a new commit.

**Comment by HaraldPanten** [comment]
OK!

Waiting for the merge, then 👍

**Comment by ValentinVinagre** [comment]
@pedrobaeza it's okay this PR?

**Comment by pedrobaeza** [comment]
Well, I only talked for solving your CI problem, but on the module, I can't say. Merging due to existing reviews:

/ocabot merge nobump
/ocabot migration pos_product_display_default_code

**Pull request merged**
