### PR TITLE
[8.0][pos_pricelist] Fix deprecated os.except_osv

### PR DESCRIPTION
**Pull request by zamberjo**
Replaced by openerp.exceptions.Warning as UserError.

### CODE REVIEW

**Comment by legalsylvain** [comment]
Hi.
Why this is a fix?
Is it not working in v8 ?
Regards.

**Comment by zamberjo** [comment]
Currently it gives error. If you look at `osv` it is not in the imports.

**Review by rousseldenis — APPROVED** [review]
Makes sense.

**Comment by legalsylvain** [comment]
Thanks and sorry for the late. thanks @rousseldenis for the review.

/ocabot merge

**Pull request closed without merging**
