### PR TITLE
12.0 mig pos loyalty

### PR DESCRIPTION
**Pull request by wpichler**
#344 is the original PR - was closed because author is not going to work on it anymore. This is the new PR for it - at time no changes from the original PR.
Odoo 13 CE does not seem to have pos_loyalty in CE - so no backport is possible

### CODE REVIEW

**Comment by flotho** [comment]
Hi @wpichler 

Happy to read that you're sharing some customer profile with us ;-)
Could you tell me a bot more regarding the maturity of this PR, I would like to test and help for the review

**Comment by wpichler** [comment]
Hi @flotho 
Thanks for the help on the preview
What do you mean with sharing a customer profile ?

We tested the module in this PR on a current odoo v12 - and it does work. We do not have it in production environment yet.

**Comment by flotho** [comment]
We worked together on magento connector, we'll also work on PoS
maybe my english is not correct but your customers seems to have the same challenges as ours ;-)

**Comment by wpichler** [comment]
Ah - ok - this is correct - maybe we should exchange some more profile data - maybe we could share some more work...

I thought that i have forgotten some sensitive customer data in the code...

**Comment by ivantodorovich** [comment]
Tests need fixing. They're failing in travis

**Comment by newtratip** [comment]
Hello @wpichler

I would like to help review this PR.  Could you check ci/runbot and travis-ci ? I  will test this module after that.

Thank you for open PR again :)

**Comment by legalsylvain** [comment]
Hi @wpichler what is the state of this PR ? regarding ci & runbot. Do you need some help ? 

thanks !

**Review by legalsylvain — CHANGES_REQUESTED** [review]
I just tested locally. 
- The settings in the back office seems OK
- in the front office, the computation of point is also OK and the reward button is enlighted when total points are reached

however when I click on any rewards, nothing is done : 

image

 Is this PR Still WIP ?

**Comment by wpichler** [comment]
Hi,

PR is abondend - you can take over if you want

**Comment by hitrosol** [comment]
I try https://github.com/Callino/pos/tree/12.0-mig-pos_loyalty
on my local and it's functionally works well..

image

What the missing is the information about the Loyalty Point Program in the Printout Receipt.
Thanks...

**Comment by hitrosol** [comment]
I think, you have to check the "Available in POS" to make the reward item effective to the POS Order.

image


image

The features on this module are really useful. It's too bad it's not ready yet.
it's work well in my local

**Comment by dsolanki-initos** [comment]
@wpichler Can you make Travis happy?

**Comment by dsolanki-initos** [comment]
@wpichler it would be nice if could we complete this module in v12.

**Comment by wpichler** [comment]
hi @dsolanki-initos - i will look into it today - thanks for your friendly reminder

**Comment by dsolanki-initos** [comment]
@wpichler it would be nice if could we complete this module in v12.

**Comment by wpichler** [comment]
found the unit tests problem - the sample products and customers did changed. Updated the unit tests to reflect these changes, now it should not fail any more...

**Comment by dsolanki-initos** [comment]
Hi @wpichler Travis is failed because of the web_tour.tour could you check this link 
https://app.travis-ci.com/github/OCA/pos/jobs/550907114#L2110

**Comment by dsolanki-initos** [comment]
Hi @wpichler 
It would be nice if you could fix the failed checks

**Comment by dsolanki-initos** [comment]
@wpichler Can you please fix the failed checks ?

**Comment by dsolanki-initos** [comment]
Hello @wpichler,
Can you please fix the failed checks ?

**Comment by wpichler** [comment]
Sorry - no time for it - can you take over - or should we close it ?

**Comment by flotho** [comment]
Hi @dsolanki-initos @wpichler maybe we could try to set it as a beta release it should ease the first integration.
@legalsylvain what's the point o view of OCA for integrating such a good work in an alpha state ?

Regards

**Comment by legalsylvain** [comment]
Hi. CI should be green. It's a must have to merge for all OCA repo.
Otherwise no problem to accept alpha / beta module, as far as there is a quick  text in a roadmap file to say what are the next steps.

Regards.

**Comment by eLBati** [comment]
Taking care of this at https://github.com/OCA/pos/pull/762

**Comment by dsolanki-initos** [comment]
@wpichler can you please check the failed?

**Comment by dsolanki-initos** [comment]
@wpichler can you please check the failed checks?

**Comment by dsolanki-initos** [comment]
@wpichler can you please check the failed checks?

**Comment by wpichler** [comment]
I've now disabled IoT Box support by setting proxy_ip to None in pos.config - so it should not wait for IoT Box on startup

**Comment by dsolanki-initos** [comment]
@wpichler can we see travis green?

**Comment by dsolanki-initos** [comment]
@wpichler can we see the Travis green?

**Comment by dsolanki-initos** [comment]
@wpichler Can we make Travis to green?

**Comment by dsolanki-initos** [comment]
@wpichler can you please failed checks?

**Pull request closed without merging**
