### PR TITLE
[10.0][MIG] pos_product_template

### PR DESCRIPTION
**Pull request by hparfr**
Migrate the module and refactore part of it.

### CODE REVIEW

**Comment by hparfr** [comment]
Needs https://github.com/OCA/pos/pull/268

**Comment by bealdav** [comment]
Just functionnally tested @ https://github.com/OCA/pos/pull/266/commits/9fd2fc80e6f5df557427960ffd1516a7b8367968

var


Just works as it works in v8. Really thanks

**Review by mourad-ehm — APPROVED** [review]
Code review

**Review by PierrickBrun — APPROVED** [review]

**Review by bealdav — APPROVED** [review]

**Comment by bealdav** [comment]
I think it's now mergeable.

What do you think @legalsylvain ?  Thanks

**Comment by rafaelbn** [comment]
Please @hparfr could you squash your commints please? Let me know I will merge ASAP

**Comment by hparfr** [comment]
Hi, @rafaelbn  please use the "squash and merge" option.

**Comment by pedrobaeza** [comment]
Not possible in this case as there are commits from many people.

**Comment by hparfr** [comment]
@pedrobaeza  @rafaelbn  I'have created a new pr with theses commits squashed : #271

**Comment by pedrobaeza** [comment]
Superseeded by #271

**Pull request closed without merging**
