### PR TITLE
[14.0][IMP] pos_cash_move_reason: Restrict move reasons by pos.config. Sele…

### PR DESCRIPTION
**Pull request by ilyasProgrammer**
…ct first journal by default when move reason is selected in the wizard.

### CODE REVIEW

**Review by legalsylvain — COMMENTED** [review]
Hi. thanks for your improvment.

I understand your need, but the current implementation requires extra configuration. I mean, user has to configure all the ``allowed_config_ids`` for all the pos.move.reason ? Otherwise, nothing willl works.

what about to change the domain with something like : 

```
'|', 
                        ("allowed_pos_ids", "in", self.session_id.config_id.ids),
                        ("allowed_pos_ids", "=", False),
```

**Review by francesco-ooops — APPROVED** [review]
functional review ok!

**Comment by francesco-ooops** [comment]
@legalsylvain looks good to you? :)

**Review by legalsylvain — APPROVED** [review]
LGTM, code review / no test.

/ocabot merge minor

**Pull request merged**
