### PR TITLE
[16.0][FIX] pos_partner_birthdate: partner birthdate field wasn't being saved from PoS

### PR DESCRIPTION
**Pull request by suker**
Steps to reproduce:

1. Install module and open a pos session
2. Select a customer and edit its birthdate field
3. Check that birthdate field has not been saved on frontend/backend

### CODE REVIEW

**Comment by suker** [comment]
It seems that in this change https://github.com/odoo/odoo/commit/c585d82dc34c99cafee645c5a306f1a795b06c0c they made partner editor screen reactivity changing its logic.

**Review by ecino — APPROVED** [review]
Thank you for the fix, code LGTM, didn't tested it yet.  :+1:

**Comment by suker** [comment]
Testing functionality I found a bug on partner creation in a pos session when birthdate field is empty, its already fixed in this [commit](a1fb7027de85c9827a034372035b33755d34db48)

image

**Comment by suker** [comment]
@ecino can you take a look please?

**Review by ecino — APPROVED** [review]
:+1:

**Comment by suker** [comment]
@OCA/pos-maintainers changes approved, can you merge it?

**Review by chienandalu — APPROVED** [review]
/ocabot merge patch

**Pull request merged**
