### PR TITLE
[17.0][MIG]pos_default_partner: Migration to 17.0

### PR DESCRIPTION
**Pull request by rousemilano**
@pedrobaeza buenas noches, solicito review tecnico. Muchas gracias

### CODE REVIEW

**Comment by legalsylvain** [comment]
Same comment as hère https://github.com/OCA/pos/pull/1078#issuecomment-1800503582

**Comment by rousemilano** [comment]
> Same comment as hère [#1078 (comment)](https://github.com/OCA/pos/pull/1078#issuecomment-1800503582)

Finish, thanks.

**Comment by rousemilano** [comment]
@OCA-git-bot  review técnico

**Comment by flotho** [comment]
runboat is not run for this PR ?

**Review by smcqueen81 — APPROVED** [review]
Functional Ok

**Pull request closed without merging**
