### PR TITLE
[12.0][MIG] pos_reset_search

### PR DESCRIPTION
**Pull request by Fkawala**
Migration of pos_reset_search from v9 to v12.

### CODE REVIEW

**Review by flotho — APPROVED** [review]
LGTM

Thanks a lot for this PR

**Comment by Fkawala** [comment]
Thank you for the review @flotho!

**Comment by Fkawala** [comment]
@vvrossem @robinkeunen would one of you have a sec' to review this PR, please? thank you!

**Review by ivantodorovich — APPROVED** [review]

**Review by vvrossem — APPROVED** [review]

**Pull request merged**
