### PR TITLE
[14.0][ADD] pos_report_discount: add module

### PR DESCRIPTION
**Pull request by dessanhemrayev**
This module add discount to pivot POS orders

### CODE REVIEW

**Review by francesco-ooops — APPROVED** [review]
LGTM!

@legalsylvain what do you say?

**Review by geomer198 — APPROVED** [review]
LGTM!

**Comment by francesco-ooops** [comment]
@OCA/pos-maintainers good for you?

**Review by ivantodorovich — APPROVED** [review]

**Pull request merged**
