### PR TITLE
Revert "[REM][8.0] remove pos_remove_pos_category Fix : #200"

### PR DESCRIPTION
**Pull request by legalsylvain**
Reverts OCA/pos#201

See : https://github.com/OCA/pos/issues/200#issuecomment-324257572

CC : @StefanRijnhart, @pedrobaeza

### CODE REVIEW

**Review by hparfr — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Are you sure this is correctly working? Isn't the new approach better to be implemented also here?

**Review by bealdav — APPROVED** [review]

**Comment by bealdav** [comment]
New approach is for v10 as i understood ?

**Comment by StefanRijnhart** [comment]
This version is not affected by the bug, but @Cedric-Pigeon's solution is of course much more elegant. It can also be applied here.

**Comment by bealdav** [comment]
Ok @StefanRijnhart for the precision.

We use this module with this code since almost 3 years  (150 000 sales by year) and we'll prepare migration to v10.

I'm happy to see @Cedric-Pigeon elegant solution. On our side we think we must invest in v10 in next weeks. v8 is an old version that must be kept working.

But for elegance, maybe we could think v10 or v11, or in another PR. Don't you think ?

**Comment by pedrobaeza** [comment]
New approach will avoid other possible side effects, but if no one wants to implement it and this working fine, we revert it as is.

**Comment by bealdav** [comment]
@legalsylvain 

error here is:

Installing Odoo https://github.com/odoo/odoo/archive/8.0.tar.gz
https://codeload.github.com/odoo/odoo/tar.gz/8.0:
2017-08-23 12:30:31 ERROR 500: Internal Server Error.

Maybe you can merge, as 2 approve and continuous-integration/travis-ci/pr green, or reload test

Thanks

**Comment by pedrobaeza** [comment]
Rebuilding

**Review by StefanRijnhart — APPROVED** [review]
Fine by me to keep this 'as is'.

**Pull request merged**
