### PR TITLE
[ADD] 7.0 'pos_order_pricelist_change'

### PR DESCRIPTION
**Pull request by legalsylvain**
Propose 'pos_order_pricelist_change' in 7.0 serie.

This PR has been previously approved on launchpad:
- @pedrobaeza :+1: 2014-09-23 

Ref: https://code.launchpad.net/~sylvain-legal/openerp-pos/7.0_fix_pos_change_pricelist/+merge/228833

### CODE REVIEW

**Comment by max3903** [comment]
POT file is missing

**Comment by legalsylvain** [comment]
@max3903 : Thanks for your review. Pot file Fixed.

**Comment by max3903** [comment]
You have an error in your test. Travis didn't catch it.

ImportError: cannot import name test_pos_order_pricelist_change

**Comment by legalsylvain** [comment]
Ow, thanks. 
Pretty weird that Travis did'nt failed. Do you know why ?

**Comment by max3903** [comment]
I have no idea. I reported it in this issue: https://github.com/OCA/maintainer-quality-tools/issues/137

:+1:

**Comment by legalsylvain** [comment]
Thanks for the bug report.

**Pull request merged**
