### PR TITLE
[ADD] Make pos session available when selecting pickings

### PR DESCRIPTION
**Pull request by StefanRijnhart**
This way, in my customizations I can select pickings that come from the source location that is associated with the POS.

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]
Thanks. I propose fast merge for such trivial PR, If you're agree.

**Comment by StefanRijnhart** [comment]
Yes please ;-)

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Change module version number. You're changing signature of the methods, but I don't think this is going to be a huge problem.

**Comment by StefanRijnhart** [comment]
@pedrobaeza version number updated. I don't think changing the signature is a big deal. Module was merged only nine days ago.

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Let's merge this for avoiding an "invalid" signature in stable.

**Pull request merged**
