### PR TITLE
[14.0][NEW] pos_customer_tree_view_vat

### PR DESCRIPTION
**Pull request by mileo**
Signed-off-by: Luis Felipe Mileo <mileo@kmee.com.br>

### CODE REVIEW

**Review by legalsylvain — COMMENTED** [review]
I think the name is not explicit. (We dont know if its about customer or product) Something like poste_customer_tree_view_vat could be better. Dont you think ?

**Comment by legalsylvain** [comment]
Naïve question : why do you need the vat of the customer on this screen ?

**Comment by mileo** [comment]
> screen

To help the user search by VAT, for example:

image

**Comment by mileo** [comment]
> I think the name is not explicit. (We dont know if its about customer or product) Something like poste_customer_tree_view_vat could be better. Dont you think ?

Renamed =D

**Review by ivantodorovich — APPROVED** [review]

**Pull request merged**
