### PR TITLE
[16.0][FIX] pos_order_reorder: Fix banner

### PR DESCRIPTION
**Pull request by Bearnard21**
Fix banner

### CODE REVIEW

**Review by Aldeigja — APPROVED** [review]
LGTM

**Review by dessanhemrayev — APPROVED** [review]
LGTM

**Comment by CetmixGitDrone** [comment]
/ocabot merge nobump
Merged by @ivs-cetmix

**Comment by CetmixGitDrone** [comment]
/ocabot rebase
Rebased by @ivs-cetmix

**Comment by CetmixGitDrone** [comment]
/ocabot merge nobump
Merged by @ivs-cetmix

**Pull request merged**
