### PR TITLE
[14.0][ADD] pos_order_product_search

### PR DESCRIPTION
**Pull request by ilyasProgrammer**
Search for POS orders by product fields. Name, barcode, internal reference.

### CODE REVIEW

**Review by francesco-ooops — APPROVED** [review]
Functional review ok

**Comment by francesco-ooops** [comment]
@legalsylvain does it look good to you? 
Thanks for the reviews :)

**Review by elvise — APPROVED** [review]
LGTM!

**Review by ivantodorovich — APPROVED** [review]
LGTM

**Pull request merged**
