### PR TITLE
[17.0][MIG] pos_lot_selection: Migration to 17.0

### PR DESCRIPTION
**Pull request by nguyenminhchien**
ref: BSRD-704

### CODE REVIEW

**Comment by Fabrizio1305** [comment]
It works 
(but I have a bug that I think is not related to the module, but to odoo, as it happens also without the module)
Tested flow:

1. activate lots on products
2. take a product available in POS, and update qty to create an entry with a LOT (make sure the lot number doesn't exist yet for any product), make sure the product doesn't have qty in stock without a LOT (to avoid inconsistencies). 
Create a second and third LOT on the same product, one of them with quantities and one without
3. open POS
4. add that product to a cart the standard way
5. on the lot selection popup, a drop down menu should appear with the choice of lots that are in stock, choose one of them
7. finalize the transaction by paying in cash and closing the POS
8. and double check that the proper product and lot has been taken out of stock (inventory moves)

The flow worked, but on point 8, in the POS session data I have the correct lot sold, but in the inventory app I have another lot being delivered. I think this is an odoo bug rather than this module's bug as it also happens without the module.
tested with and without #1105 pos_lot_barcode

**Comment by etobella** [comment]
@nguyenminhchien I made the migration but made it compatible with an offline PoS. Do you prefer that I make a PR directly to your PR or should I made a new one (I would keep part of your code regarding to tests for example)

**Comment by nguyenminhchien** [comment]
> @nguyenminhchien I made the migration but made it compatible with an offline PoS. Do you prefer that I make a PR directly to your PR or should I made a new one (I would keep part of your code regarding to tests for example)

Please create a pull request to my branch` nguyenminhchien:17.0-mig-pos_lot_selection`, thanks.

**Comment by etobella** [comment]
I made the PR:

https://github.com/nguyenminhchien/pos/pull/3

Can you review it?

**Comment by nguyenminhchien** [comment]
> I made the PR:
> 
> [nguyenminhchien#3](https://github.com/nguyenminhchien/pos/pull/3)
> 
> Can you review it?

@etobella hi, i merged your commit but the test was failed, please check it. thanks.

**Comment by etobella** [comment]
I made the fix, it was just a small typo error on the last change :disappointed:

**Comment by cvinh** [comment]
> > I made the PR:
> > [nguyenminhchien#3](https://github.com/nguyenminhchien/pos/pull/3)
> > Can you review it?
> 
> @etobella hi, i merged your commit but the test was failed, please check it. thanks.

Hello, new PR here https://github.com/nguyenminhchien/pos/pull/4

**Review by cvinh — APPROVED** [review]
Functional tests ok

**Review by etobella — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
