### PR TITLE
[FIX][8.0] pos_order_to_sale_order 

### PR DESCRIPTION
**Pull request by legalsylvain**
**main fixes**
for the time being, the user can click to create a sale order, and during the creation , click again, and create duplicated items.
With this PR, the user has to wait for the result of the creation of the sale order, calling ``instance.web.blockUI`` function

**other fixes**
- remove ``console.log call``
- do not import js files in backend

CC: @quentinDupont

### CODE REVIEW

**Comment by quentinDupont** [comment]
I don't have the knowledge to understand "do not import js files in backend", otherwise thank's for this PR :+1:

**Review by quentinDupont — APPROVED** [review]

**Review by hparfr — APPROVED** [review]

**Comment by rafaelbn** [comment]
I think we should merge this one

Travis :red_circle: is are LINT errors: https://travis-ci.org/OCA/pos/jobs/466907255

> pylint expected errors 0, found 18!

**Review by rafaelbn — APPROVED** [review]
Ready to merge :+1:  thanks @legalsylvain 

cc @chienandalu

**Comment by chienandalu** [comment]
Well, lint errors are just rst syntax errors on other modules. We can merge this (not affected), although `8.0` maintainers should fix those to get a green branch as they're quite trivial.

**Review by chienandalu — APPROVED** [review]

**Pull request merged**
