### PR TITLE
 [ADD] pos_product_sort : 12.0 module to order products by name

### PR DESCRIPTION
**Pull request by legalsylvain**
Trivial module to sort products by name in the point of sale.

This module extends Odoo Point Of Sale features.

By default since v9.0 refactor, products are ordered by sequence, code, name in the Point of Sale Front End :

point_of_sale_sequence_order

This behavior is correct for a point of sale with a few products, but does not correspond to the needs of the cashiers, when there are thousands of products.

Once installed, the products are ordered by name :

point_of_sale_name_order

CC : @quentinDupont @grap

### CODE REVIEW

**Review by ivantodorovich — APPROVED** [review]
LGTM :+1:

Although as a suggestion, maybe you could rename the module to `pos_product_order` and make it configurable in the `pos.config` with a selection field between sequence and name (and why not code, price.. ?)

Not blocking though ;) take it or leave it

**Review by rvalyi — APPROVED** [review]
LGTM

**Comment by legalsylvain** [comment]
Hi @ivantodorovich . THanks for your review. Regarding the name, i previously used "order" but i's confusing because it is used for pos order, purchase, sale.
Int the meantime, all the OCA modules are using "sort". 
Regarding settings, it's not in the scope of this PR, but I can rename the module into "pos_product_sort" to allow futur PRs, and add your remark in a roadmap section.
What do you think ?
Kind regards.

**Review by hparfr — APPROVED** [review]
LGTM

**Review by houssine78 — APPROVED** [review]

**Comment by ivantodorovich** [comment]
> Hi @ivantodorovich . THanks for your review. Regarding the name, i previously used "order" but i's confusing because it is used for pos order, purchase, sale.
> 
> Int the meantime, all the OCA modules are using "sort". 
> 
> Regarding settings, it's not in the scope of this PR, but I can rename the module into "pos_product_sort" to allow futur PRs, and add your remark in a roadmap section.
> 
> What do you think ?
> 
> Kind regards.

Sounds good! 👍🏻

**Review by quentinDupont — APPROVED** [review]

**Review by fcayre — APPROVED** [review]

**Pull request merged**
