### PR TITLE
[FIX] pos_order_return is not computing correctly substotals on return

### LINKED ISSUE #508: [12.0]POS ORder Return is not computing correctly fianancial parts
Just made a test here : http://3426910-480-76ca7e.runbot2-3.odoo-community.org/web#id=2&action=315&model=pos.order&view_type=form&menu_id=176
As you can see :+1: 
image
picte_subtotal and price_subtotal_incl are not negative , this is not the native behaviour and cause great troubles with cash control because account.move are no more balanced.

### PR DESCRIPTION
**Pull request by ivantodorovich**
Fixes https://github.com/OCA/pos/issues/508

### CODE REVIEW

**Comment by ivantodorovich** [comment]
ping @flotho @chienandalu @legalsylvain

**Review by legalsylvain — APPROVED** [review]
Thanks @ivantodorovich ! 

(Code review / no test)

**Review by chienandalu — APPROVED** [review]
Thanks :)

**Comment by chienandalu** [comment]
Please @flotho , confirm the patch works for you

**Review by flotho — APPROVED** [review]
successfully tested with tresult
image

http://3428088-509-bc6e26.runbot2-2.odoo-community.org/web?#id=2&active_id=1&model=pos.order&view_type=form&menu_id=193

LGTM

**Comment by flotho** [comment]
Thanks to all of you.

**Pull request merged**
