### PR TITLE
[14.0][MIG] pos_order_mgmt: Migration to 14.0

### PR DESCRIPTION
**Pull request by zamberjo**
Note: [PR](https://github.com/OCA/pos/pull/981) is required to avoid error when testing the return with the "In real time" configuration parameter.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@zamberjo please rebase now that the other PR is merged.

**Comment by zamberjo** [comment]
> @zamberjo please rebase now that the other PR is merged.

Done. I had to set `"development_status": "Alpha",` so that it would run the tests.

**Comment by pedrobaeza** [comment]
OK. I think `pos_order_return` deserves to be promoted to at least beta (but better to stable), but for now it's enough.

**Review by belenaures — APPROVED** [review]
LGTM

**Review by chienandalu — APPROVED** [review]
Good job! @zamberjo :+1:

**Pull request merged**
