### PR TITLE
[FIX] init calculation of taxes

### PR DESCRIPTION
**Pull request by JavierIniesta**
This PR fixes the init calculation of taxes when you install this addon.

### CODE REVIEW

**Comment by JavierIniesta** [comment]
@ah-taktik If there was orders before installing this addon, the method _install_tax_detail was launched before adding the pos.order.tax. With this change, it will be executed after.

**Comment by JavierIniesta** [comment]
product_taxes_rel is related with product templates not product products. So I added two joins to the SQL statement.

**Comment by pedrobaeza** [comment]
Fields names doesn't help too much on discovering template/product duality...

:+1:

**Comment by antespi** [comment]
:+1: Cool, tested on local environtment

**Comment by rafaelbn** [comment]
Review on runbot, working in production enviroment already
:+1: 
@antespi please check it

**Pull request merged**
