### PR TITLE
[11.0] MIG: pos_product_template

### PR DESCRIPTION
**Pull request by hugosantosred**
Migration of module pos_product_template to V11

### CODE REVIEW

**Comment by imjaypatel** [comment]
Please merge this pull request as soon as possible. Thanks

**Comment by pedrobaeza** [comment]
@imjaypatel as indicated in the other PR, please review it.

**Comment by imjaypatel** [comment]
> @imjaypatel as indicated in the other PR, please review it.

How to I review of that PR?

**Comment by chienandalu** [comment]
Hi, @imjaypatel You can either test functionality or code and give your feedback here.

**Comment by cvinh** [comment]
We use it in production :+1: :+1: 
@hugosantosred could you include last commits in v10 (depends on pos_fix_search_limit)? : 
https://github.com/OCA/pos/commit/7296250c5d50b26aa63ac8d33d4ebd376e8b82d7#diff-1cc6d3c579b0dc8dda40015af67fa992
I made a PR for migrating pos_fix_search_limit to v11 here https://github.com/OCA/pos/pull/349

**Comment by chienandalu** [comment]
> We use it in production  
> @hugosantosred could you include last commits in v10 (depends on pos_fix_search_limit)? :
> [7296250#diff-1cc6d3c579b0dc8dda40015af67fa992](https://github.com/OCA/pos/commit/7296250c5d50b26aa63ac8d33d4ebd376e8b82d7#diff-1cc6d3c579b0dc8dda40015af67fa992)
> I made a PR for migrating pos_fix_search_limit to v11 here #349

I don't like much the monkeypatching in that fix. Isn't there a better way to achieve the same goal?

**Comment by kanakinfo** [comment]
@chienandalu We are tested and review this migrated module. Can you please merge it. Thank you.

**Comment by legalsylvain** [comment]
What is the state of this PR. did you took into account @chienandalu remarks ?

**Pull request closed without merging**
