### PR TITLE
[16.0][MIG] pos_event_sale: Migration 16.0

### PR DESCRIPTION
**Pull request by BT-dmoreno**

### CODE REVIEW

**Comment by ivantodorovich** [comment]
Hey @BT-dmoreno , thanks for migrating this module!

I haven't done a full review yet, though.. could you squash (all or some of) your migration commits into `[16.0][MIG] pos_event_sale: Migration to 16.0` ?

I see some noise in them, like: `[IMP] Remove non-used variable` is patching code introduced in  `[IMP] Prevent race condition on payment screen validate button`, you might as well squash them.

Ideally, keep only `[16.0][MIG] pos_event_sale: Migration to 16.0` along with some totally optional and well described extra commits 🙏🏻

**Comment by BT-dmoreno** [comment]
Hi @ivantodorovich thanks for your comment! Finally I got some time to apply your suggestion, I have squashed all my last commits into a single one, it should be fine now.

**Comment by ivantodorovich** [comment]
Thanks @BT-dmoreno !

It looks like test tours are failing, could you check?

**Comment by maq-adhoc** [comment]
@BT-dmoreno  How are you?
Can I help you with this migration? If not I can continue your work in another PR. 
I understand that you are close to finish it.

**Comment by BT-dmoreno** [comment]
@maq-adhoc I have not time at the moment to continue with this module. Yes, feel free to continue it yourself please.

**Comment by maq-adhoc** [comment]
> @maq-adhoc I have not time at the moment to continue with this module. Yes, feel free to continue it yourself please.

im start work in https://github.com/OCA/pos/pull/1205

**Pull request closed without merging**
