### PR TITLE
[13.0][NEW] pos_invoice_required

### PR DESCRIPTION
**Pull request by robyf70**
New module pos_invoice_required to permit to disable/optional/mandatory invoice selection as per PoS

### CODE REVIEW

**Comment by cvinh** [comment]
Hi @robyf70 thanks for pushing this module.
Could you do a little improvement : set order.to_invoice to True by default in case the option is 'required' ?

**Comment by robyf70** [comment]
> Hi @robyf70 thanks for pushing this module. Could you do a little improvement : set order.to_invoice to True by default in case the option is 'required' ?

I've just pushed the changes

**Review by francesco-ooops — CHANGES_REQUESTED** [review]
tested option "require invoice", got this error at checkout: 

image

**Comment by robyf70** [comment]
> tested option "require invoice", got this error at checkout:
> 
> image

Can you please set the invoice journal in your PoS and make another test?

**Comment by francesco-ooops** [comment]
> Can you please set the invoice journal in your PoS and make another test?

I think you should rather add a verification that "invoice journal" is set in order to enable "require invoice"

**Comment by robyf70** [comment]
> > Can you please set the invoice journal in your PoS and make another test?
> 
> I think you should rather add a verification that "invoice journal" is set in order to enable "require invoice"

Yes! Indeed! I need just a verification that this is the case

**Comment by francesco-ooops** [comment]
yes, that was the issue

image

Imho the three options should only be visible once "Invoicing" is selected

**Comment by robyf70** [comment]
> > > Can you please set the invoice journal in your PoS and make another test?
> > 
> > 
> > I think you should rather add a verification that "invoice journal" is set in order to enable "require invoice"
> 
> Yes! Indeed! I need just a verification that this is the case

Ok! I did the changes to make the invoicing set to true and readonly when invoice is mandatory as well as the invoice journal became mandatory on the same condition,

**Comment by francesco-ooops** [comment]
@robyf70 doesn't look to me like the correct flow [VIDEO](https://recordit.co/4e06LnYpGI)

The user should activate the invoice flag first, then whether it's required or not

**Comment by robyf70** [comment]
> 

You are right! I'm changing the flow

**Comment by robyf70** [comment]
@francesco-ooops Done

**Comment by francesco-ooops** [comment]
@robyf70 I can't seem to be able to access runboat for some reason?

**Comment by robyf70** [comment]
> @robyf70 I can't seem to be able to access runboat for some reason?

No idea why

**Comment by francesco-ooops** [comment]
@robyf70 can you try a rebase?

**Comment by robyf70** [comment]
> @robyf70 can you try a rebase?

Let's see how it goes now

**Comment by robyf70** [comment]
@francesco-ooops Do any comment regarding the last commit?

**Review by francesco-ooops — APPROVED** [review]
functional ok!

**Comment by robyf70** [comment]
@legalsylvain Can you please merge ?

**Comment by robyf70** [comment]
@legalsylvain Can you please reopen and merge?

**Comment by matteoopenf** [comment]
@robyf70  can you check run boat? and after try to do a review?

**Comment by robyf70** [comment]
> @robyf70 can you check run boat? and after try to do a review?

Should be all fine now

**Review by matteoopenf — APPROVED** [review]
functional review ok

**Pull request merged**
