### PR TITLE
[FIX] Fixed @api.constrains issue

### PR DESCRIPTION
**Pull request by krunal267**
Task URL:

https://www.druidoo.io/web#id=2765&model=project.task&view_type=form&menu_id=

### CODE REVIEW

**Comment by krunal267** [comment]
The following Warning message is coming while creating or updating pos.order.

**2020-06-11 10:43:20,185 4105 WARNING odoo12_test odoo.models: method pos.order._check_partner: @constrains parameter 'require_customer' is not writeable**

It's because the field 'require_customer' is store=False.

**Review by ivantodorovich — APPROVED** [review]

**Review by legalsylvain — APPROVED** [review]
LGTM

/ocabot merge patch

**Comment by pedrobaeza** [comment]
It seems it's not triggered:

/ocabot merge patch

**Comment by ivantodorovich** [comment]
> It seems it's not triggered:
> 
> /ocabot merge patch

Yeah, it doesn't work if the command is written in the review comments

**Comment by pedrobaeza** [comment]
@legalsylvain it was already merged.

**Comment by legalsylvain** [comment]
Sorry. Didn't refreshed the page.

**Pull request merged**
