### PR TITLE
Move module icon in static/description

### PR DESCRIPTION
**Pull request by yvaucher**

### CODE REVIEW

**Comment by legalsylvain** [comment]
Hi, 
Excuse me if my question is irrelevant, but what is the aim of this move ?
Regards.

**Comment by yvaucher** [comment]
@legalsylvain This is to make module icon visible on apps.odoo.com

**Comment by yvaucher** [comment]
See on https://www.odoo.com/apps/modules/page/1?search=pos_product_template

**Comment by legalsylvain** [comment]
Thanks for your explanation and the PR.

**Comment by pedrobaeza** [comment]
:+1: 

I fast-track.

**Pull request merged**
