### PR TITLE
[ADD] 'pos_order_load'

### PR DESCRIPTION
**Pull request by sylvainc**
Hello,

This module is in WIP, it allows salesman to search and load prexisting
orders from the POS UI.

The backup of the draft orders hasn't be implemented because
it isn't needed in our client use cases.
If you need this functionality maybe you can look at this:
https://github.com/OCA/pos/pull/5

Any comments or help appreciated,

Regards,

Sylvain

### CODE REVIEW

**Comment by legalsylvain** [comment]
Hi Sylvain, 
Thanks a lot for this PR. This is a good feature.

I tried your module and I have some questions : 
- Is it still WIP ?
- I simply tried to reload a pos order : 
  1 / I have a question about the first column "Order" : It is written "False", I don't know why. Do you want to display the name of the pos order ?
  2/ I have an error when try to select the order : 
  
  ´´´Uncaught SyntaxError: Unexpected token u´´´
- Can you fix the two minor bug on travis (this is just flake8 & pylint bugs) ?

Otherwise, the load is correct, and we can see the list of the orders.

Waiting for your answer.

**Comment by sylvainc** [comment]
Hi Sylvain,

Thank you for your feedback.
This branch is not longer maintened, last developments on this subject are here:
https://github.com/akretion/pos/tree/8.0-pos-sale-order-load

Thanks!

**Comment by legalsylvain** [comment]
OK. 
I so mark this PR as "WIP" and let it 'open' to show to the community that there is pending works.
Next Step for me. (or for other contributors)
- Review your code;
- Integrate the functionnality of pos_backup_draft_orders (V7 modules) into your code;
- Make a unic module and PR.

Kind Regards.

**Comment by legalsylvain** [comment]
done in #42. 
I close this PR.
Kind regards.

**Pull request closed without merging**
