### PR TITLE
[IMP] 14.0: pos_product_template no variant display

### PR DESCRIPTION
**Pull request by PierrickBrun**
based on https://github.com/OCA/pos/pull/812 to avoid conflicts

This allows to hide the variants in the pos_product_template variant selector (only showing the attributes). This is not the default behaviour.

Also this adds a "confirm" button as an alternative to clicking on the last variant remaining once all the attributes have a value.

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]
make sense. light code review / no test.

**Comment by legalsylvain** [comment]
Could you rebase ?

**Comment by francesco-ooops** [comment]
@legalsylvain I think we need a PR for precommit update for 14 before rebase

also one for 15 would be needed for this repo

**Review by ivantodorovich — APPROVED** [review]

**Pull request merged**
