### PR TITLE
[ADD] POS ticket logo addon

### PR DESCRIPTION
**Pull request by antespi**
Add company logo in POS ticket

### CODE REVIEW

**Comment by alexis-via** [comment]
Could you explain what your module does "better" than the native feature that display the logo on the POS ticket ?

Here is the code in the "point_of_sale" module that display the logo on the ticket:
https://github.com/odoo/odoo/blob/8.0/addons/point_of_sale/static/src/xml/pos.xml#L509

**Comment by antespi** [comment]
@alexis-via this `XmlReceipt` Qweb report is used when `iface_print_via_proxy` config is **True**:
https://github.com/odoo/odoo/blob/8.0/addons/point_of_sale/static/src/js/screens.js#L1341

But in our case, `iface_print_via_proxy` config is **False**, then `PosTicket` Qweb report is used, but company_logo is not used there:
https://github.com/odoo/odoo/blob/8.0/addons/point_of_sale/static/src/js/screens.js#L984

In other  hand, company_logo is loaded using `/web/binary/company_logo` controller that returns a 150px wide logo:
https://github.com/odoo/odoo/blob/8.0/addons/point_of_sale/static/src/js/models.js#L371
but after that logo is resized to 300px width, so a pixelled logo appears even original logo is 300px wide. That's why we override how company_logo is loaded and resized it to 260px wide because appears cut in PDF:
https://github.com/OCA/pos/pull/32/files#diff-53acffdb8ce13f8aa7f3b2b5ed3d3965R39

**Comment by alexis-via** [comment]
@antespi Thanks for your explaination ! Maybe you could write this explaination in the README.rst file, because I'm sure the users of your module would be interested by the same information :)

**Comment by antespi** [comment]
@alexis-via you're right, actually we didn't see `XmlReceipt` until you point at it, ;)

**Comment by rafaelbn** [comment]
Hi @legalsylvain @alexis-via could you review this PR please?

**Comment by pedrobaeza** [comment]
@rafaelbn, I talk with @antespi for proposing this as OCB/Odoo patch instead.

**Comment by rafaelbn** [comment]
@antespi have you proposed fix in Odoo/OCB?

**Comment by antespi** [comment]
Not yet, I'm preparing this fix. I've to argue it well using different logos sizes and proportions.

**Comment by liebana** [comment]
Is everything ok here to review @antespi @rafaelbn ?

**Comment by kossovo** [comment]
+1

**Comment by janetrp** [comment]
Tested, the logo looks really clear :+1:

**Comment by pedrobaeza** [comment]
This is still pending of an Odoo/OCB patch instead of making a new module.

**Comment by rafaelbn** [comment]
@liebana this PR is all OK and could be merged... but as @pedrobaeza said this must be patched upstream or OCB. It could help a lot if @antespi make this 2 PRs in Odoo and OCB
We have been working with this for 6 months in production enviroments.

**Comment by rafaelbn** [comment]
Could any one of you take this PR and prepare to Odoo?

**Comment by legalsylvain** [comment]
Has anybody planned to fix odoo / OCB branches ? If not, we could accept this PR that works well.
@pedrobaeza : What do you think ?

**Comment by pedrobaeza** [comment]
I prefer the patch of course. @antespi, do you have time for making it?

**Comment by rafaelbn** [comment]
This PR need just to be review one comment https://github.com/OCA/pos/pull/32#issuecomment-177179722

cc @jcarlosmontoya @JGarcia-Panach please take a look

**Comment by legalsylvain** [comment]
Hi.
Well, the patch has not been done. (after one year). I guess a patch on Odoo 8 will not be accepted now. so as this PR has been accepted, I propose to merge this PR. Otherwise, to close it.

**Comment by pedrobaeza** [comment]
We are no more interested in this module, but if you see it interesting, go ahead.

**Pull request merged**
