### PR TITLE
15.0 [MIG] pos_default_partner

### PR DESCRIPTION
**Pull request by angelgarciadelachica**
standard migration

### CODE REVIEW

**Comment by angelgarciadelachica** [comment]
@HaraldPanten @ValentinVinagre

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Review by HaraldPanten — APPROVED** [review]
LGTM

**Comment by HaraldPanten** [comment]
@chienandalu @ivantodorovich @pedrobaeza

**Pull request merged**
