### PR TITLE
[16.0][ADD] pos_receipt_replace_user_by_trigram

### PR DESCRIPTION
**Pull request by trisdoan**

### CODE REVIEW

**Review by ivantodorovich — APPROVED** [review]

**Review by francesco-ooops — CHANGES_REQUESTED** [review]
Description needs to be improved

What is the result after this module is installed? 

Is there any setup or change to UI?

**Comment by trisdoan** [comment]
Hello @francesco-ooops, thank you for your review.

I updated the descriptions as you suggested

**Comment by francesco-ooops** [comment]
Thanks! I'm just curious how is this trigram generated?

**Comment by trisdoan** [comment]
Hello @legalsylvain @simahawk @ivantodorovich, I just updated. Please help to review

### Context

As feature multi-employee-per-session is checked, without access to Employee module, users got this **AccessError(_('The fields "%s" you try to read is not available on the public employee profile.')** 

### This change
- Instead of hr.employee, `pos_trigram` is defined in `hr.employee.base`

**Review by santostelmo — APPROVED** [review]

**Review by cyrilmanuel — COMMENTED** [review]
Not an expert but LGTM

**Comment by cyrilmanuel** [comment]
hii @chienandalu, @legalsylvain , if  it's good for you, can you merge this PR ?

**Review by cyrilmanuel — APPROVED** [review]

**Comment by cyrilmanuel** [comment]
seems to have an oerror on test : 

odoo odoo.addons.pos_order_to_sale_order.tests.test_module: FAIL: TestUi.test_pos_order_to_sale_order
Traceback (most recent call last):
  File "/__w/pos/pos/pos_order_to_sale_order/tests/test_module.py", line 36, in test_pos_order_to_sale_order
    self.assertEqual(len(before_orders) + 1, len(after_orders))
AssertionError: 1 != 0

**Comment by trisdoan** [comment]
Hello @cyrilmanuel and @legalsylvain , I just rebased. It passed the checks

**Pull request merged**
