### PR TITLE
[15.0][MIG] pos_require_product_quantity: Migration to 15.0

### PR DESCRIPTION
**Pull request by asegurat15**

### CODE REVIEW

**Review by legalsylvain — CHANGES_REQUESTED** [review]
Hi. Thanks a lot d'or contributing. 

Could you : 
- respect history by following https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0

- create 2 PR. (one per module)

Thanks !

**Review by legalsylvain — CHANGES_REQUESTED** [review]
Hi. Could you respect history, by cherry picking ?

Also the title of the PR is not correct I think.

**Comment by asegurat15** [comment]
> 
Hi legalsylvain, thanks for your comments. I am studying the link https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0 to correct everything.

**Comment by asegurat15** [comment]
> Hi. Could you respect history, by cherry picking ?
> 
> Also the title of the PR is not correct I think.

Please I need help, how to do pre-commit?

**Comment by legalsylvain** [comment]
You should once : 
- install pre-commit tools locally
- run ``pre-commit install`` in your pos folder

then in each commit, the checks will be executed, and prevent to commit if failing.

Note : you can execute manually pre-commit with ``pre-commit run -a``.

regards.

**Comment by asegurat15** [comment]
> pre-commit run -a

Hi bro. I have this log to run pre-commit run -a:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/segu/src-15.0/odoo-venv/lib/python3.8/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/home/segu/src-15.0/odoo-venv/lib/python3.8/site-packages/pre_commit/main.py", line 386, in main
    return run(args.config, store, args)
  File "/home/segu/src-15.0/odoo-venv/lib/python3.8/site-packages/pre_commit/commands/run.py", line 411, in run
    for hook in all_hooks(config, store)
  File "/home/segu/src-15.0/odoo-venv/lib/python3.8/site-packages/pre_commit/repository.py", line 227, in all_hooks
    return tuple(
  File "/home/segu/src-15.0/odoo-venv/lib/python3.8/site-packages/pre_commit/repository.py", line 230, in <genexpr>
    for hook in _repository_hooks(repo, store, root_config)
  File "/home/segu/src-15.0/odoo-venv/lib/python3.8/site-packages/pre_commit/repository.py", line 205, in _repository_hooks
    return _cloned_repository_hooks(repo_config, store, root_config)
  File "/home/segu/src-15.0/odoo-venv/lib/python3.8/site-packages/pre_commit/repository.py", line 171, in _cloned_repository_hooks
    manifest_path = os.path.join(store.clone(repo, rev), C.MANIFEST_FILE)
  File "/home/segu/src-15.0/odoo-venv/lib/python3.8/site-packages/pre_commit/store.py", line 186, in clone
    return self._new_repo(repo, ref, deps, clone_strategy)
  File "/home/segu/src-15.0/odoo-venv/lib/python3.8/site-packages/pre_commit/store.py", line 143, in _new_repo
    make_strategy(directory)
  File "/home/segu/src-15.0/odoo-venv/lib/python3.8/site-packages/pre_commit/store.py", line 184, in clone_strategy
    self._complete_clone(ref, _git_cmd)
  File "/home/segu/src-15.0/odoo-venv/lib/python3.8/site-packages/pre_commit/store.py", line 156, in _complete_clone
    git_cmd('fetch', 'origin', '--tags')
  File "/home/segu/src-15.0/odoo-venv/lib/python3.8/site-packages/pre_commit/store.py", line 179, in _git_cmd
    cmd_output_b('git', *args, cwd=directory, env=env)
  File "/home/segu/src-15.0/odoo-venv/lib/python3.8/site-packages/pre_commit/util.py", line 146, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/bin/git', 'fetch', 'origin', '--tags')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    fatal: no es posible acceder a 'https://gitlab.com/PyCQA/flake8/': The requested URL returned error: 403

**Pull request closed without merging**
