### PR TITLE
[10.0][MIG] pos_default_empty_image: Migration to 10.0

### PR DESCRIPTION
**Pull request by cvinh**
Migrate pos_default_empty_image to v10

### CODE REVIEW

**Comment by cvinh** [comment]
Ooops, I did not comment my commits well... a [MIG] comment is missing

**Comment by cvinh** [comment]
@pedrobaeza you're too fast, I did a push --force... I hope I did not break anything

**Comment by pedrobaeza** [comment]
hehe, no problem, I have just changed PR title. Nothing to do with commit message nor the rest of the CIs processes, that they are automatically restarted.

**Comment by legalsylvain** [comment]
Hi @invitu , thanks for this work. The next time you port a module, could you cherry-pick the commit. ( the diff will be more easy to review).
@hpar, could you take a time to review this PR ?
thanks.

**Comment by cvinh** [comment]
@legalsylvain The module was not present in v10 branch... I don't know how to cherry-pick in that case
could anybody help on how to fix the codecov and coverage failed checks ?

**Comment by lasley** [comment]
@invitu - the cherry-picking that @legalsylvain is referring to can be automatically achieved using the [migration instructions](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0#howto). 

In this instance, the branch can be fixed by:
* resetting your local to OCA/10.0
* perform migration instructions, but do not push
* cherry pick your two commits here (9f55fad, 0e3e172) - you will likely have to resolve a lot of conflicts on the first one
* force push

**Comment by cvinh** [comment]
@lasley thanks for leading me on that case. I did the [migration instructions](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0#howto) and then force pushed my branch but I see no difference in the commit.
I did it twice ... Did I miss anything ...?

**Comment by legalsylvain** [comment]
superseded by https://github.com/OCA/pos/pull/164.

**Pull request closed without merging**
