### PR TITLE
[MIG] 14.0 pos report session summary

### PR DESCRIPTION
**Pull request by PierrickBrun**

### CODE REVIEW

**Review by ivantodorovich — APPROVED** [review]
Lgtm! Thanks!

It'd be great if you can squash translation and administrative commits

**Comment by alexis-via** [comment]
The pos session report works. But I think it should be re-designed because, in v14, o.statement_ids only has the cash journal, not the other journals (card, checks). So this report only display cash information, which is very partial.
I think it would be interesting to have some info about the pos orders (number of pos orders, total with tax, total without tax, total tax, ...)

**Comment by alexis-via** [comment]
In v14, you can call self.env['report.point_of_sale.report_saledetails'].get_sale_details(self, date_start=False, date_stop=False, config_ids=False, session_ids=session_ids)
The session_ids arg didn't exist before.
With that, you can get all the info you need.

**Comment by legalsylvain** [comment]
Hi @PierrickBrun . any news regarding @alexis-via remarks ?

**Comment by elvise** [comment]
@ivantodorovich any chance for this PR ?

**Comment by legalsylvain** [comment]
@elvise this PR needs fixing

**Comment by PierrickBrun** [comment]
done in another PR

**Pull request closed without merging**
