### PR TITLE
[13.0][pos_lot_selection] - First commit

### PR DESCRIPTION
**Pull request by msolis6686**
I am migrating the module to version 13.0, but I am stuck with a problem.
If anyone can help me, the module is already working, I just don't know how to make when selecting the product, automatically load the lot or lots available.

Sorry I'm using translator. Thank you!

image

### CODE REVIEW

**Review by msolis6686 — COMMENTED** [review]
Pylint fixes

**Review by msolis6686 — COMMENTED** [review]
pylint fixes v2.0

**Review by msolis6686 — COMMENTED** [review]
pylint fixes v3

**Review by msolis6686 — COMMENTED** [review]
pylint fixes v3.1

**Review by msolis6686 — COMMENTED** [review]
pylint fixes v3.2

**Review by msolis6686 — COMMENTED** [review]
pylint fixes v3.3

**Review by msolis6686 — COMMENTED** [review]
pylint fixes v3.4

**Review by msolis6686 — COMMENTED** [review]
pylint fixes v3.5

**Review by msolis6686 — COMMENTED** [review]
pylint fixes v3.6

**Review by chienandalu — COMMENTED** [review]
Hi, @msolis6686 Welcome and thanks for your effort.

You should follow OCA guidelines in order to do migrations. It will ease your workflow and others revision of your contribution: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0

In the other hand, I'd check if the module is really needed. In regular B2C workflows, lots will be autoassigned according to your removal strategies. You just need to configure your picking types accordingly.

**Pull request closed without merging**
