### PR TITLE
[17.0][MIG] pos_product_template: Migration to 17.0

### PR DESCRIPTION
**Pull request by etobella**
Refactorized using new OWL logic

/ocabot migration pos_product_template

@cvinh @luisDIXMIT

### CODE REVIEW

**Comment by pedrobaeza** [comment]
/ocabot migration pos_product_template

Please check CI

**Comment by etobella** [comment]
@pedrobaeza error is unrelated. All tests are failing on 17.0. Fixed here https://github.com/OCA/pos/pull/1179

**Comment by pedrobaeza** [comment]
You can rebase now.

**Review by cvinh — APPROVED** [review]
Tested on runboat

**Comment by luisDIXMIT** [comment]
Tested on Runboat. There are two functionalities in the README file that may be failing. On one hand, the README file explains that if a product has variants, the number of variants should be shown instead of the price. However, nothing is displayed.

image

On the other hand, the variant attributes should function as filters, as explained in the README file, but it appears not to be working.

image

Could you please check this, @etobella? Maybe I'm interpreting the README file incorrectly. Thanks.

image

**Comment by etobella** [comment]
@luisDIXMIT Reviewed, thanks!

**Comment by SapphireHotS** [comment]
Hello @etobella , is it functional now?

**Comment by cvinh** [comment]
> Hello @etobella , is it functional now?

We use it in production for weeks, I guess it's ok

**Review by cvinh — APPROVED** [review]

**Review by luisDIXMIT — APPROVED** [review]
LGTM!

**Comment by pedrobaeza** [comment]
@etobella can you please rebase to check if the problem is transient?

**Comment by etobella** [comment]
Seems a change on Odoo

**Comment by pedrobaeza** [comment]
:facepalm:

**Comment by etobella** [comment]
It seems that product_lot_barcode and product_lot_selection are colliding for some reason. I will investigate

**Comment by FernandoRomera** [comment]
> It seems that product_lot_barcode and product_lot_selection are colliding for some reason. I will investigate

Could this be https://github.com/OCA/pos/pull/1232 the cause?

**Pull request merged**
