### PR TITLE
WIP [13.0][MIG] pos_session_pay_invoice

### PR DESCRIPTION
**Pull request by acsonefho**
Migration of `pos_session_pay_invoice` from `12.0`.

Still WIP because migration of module `account_cash_invoice` not already finished.
https://github.com/OCA/account-payment/pull/392

### CODE REVIEW

**Comment by etobella** [comment]
You need to add account-payment on oca_dependencies.txt

**Comment by etobella** [comment]
@acsonefho Do you need help with this migration?

**Comment by acsonefho** [comment]
> @acsonefho Do you need help with this migration?

@etobella I don't need help technically, I just don't have time for this PR now (even if it's sometime small to fix it).
If you need this or if you have time, don't hesitate to finish it. It's not a problem for me.

Thank you :)

**Comment by olgamarcocb** [comment]
Superseded at #674 following the comments of the author

**Pull request closed without merging**
