### PR TITLE
[14.0][BACKPORT] pos_partner_birthdate backport from 16.0 to 14.0

### PR DESCRIPTION
**Pull request by GabbasovDinar**

### CODE REVIEW

**Review by geomer198 — APPROVED** [review]
LGTM

**Review by Aldeigja — APPROVED** [review]
Functional Ok

**Comment by Aldeigja** [comment]
@OCA/pos-maintainers good for merge?

**Comment by legalsylvain** [comment]
Diff review / no test.
LGTM. thanks for your contribution.

/ocabot merge patch

**Pull request merged**
