### PR TITLE
[16.0][FIX]pos_partner_firstname: Create and Update partner

### PR DESCRIPTION
**Pull request by DorianMAG**
- Add useState and add missed fields
- Update saveChanges() method
- Update template
- Remove jquery code

### CODE REVIEW

**Review by chienandalu — CHANGES_REQUESTED** [review]
Looks good. In the formal side:

- Don't put versions on the commit messages
- Squash your commits into a single one

**Review by CLEBORGNEAPIK — APPROVED** [review]

**Comment by DorianMAG** [comment]
> Looks good. In the formal side:
> 
>     * Don't put versions on the commit messages
> 
>     * Squash your commits into a single one
It' s done
Regards

**Review by JulienMartinez — APPROVED** [review]
LGTM

**Review by FrancoMaxime — APPROVED** [review]
LGTM: code review

**Review by robyf70 — APPROVED** [review]
LGTM

**Review by etobella — APPROVED** [review]
TEsted functionally

**Review by ivantodorovich — APPROVED** [review]

**Comment by ivantodorovich** [comment]
retry
/ocabot merge patch

**Pull request merged**
