### PR TITLE
[ADD] pos_container

### PR DESCRIPTION
**Pull request by remytms**
This module allows to handle use of reusable containers in POS,
this is useful to handle selling product in bulk without having to calculate
the tare of the container.

Each container is identified by a barcode, the weight is stored in Odoo.

See Readme for more information.

I'm not the author, just the commiter. Credits to :
- @robinkeunen 
- @PierrickBrun
- @vvrossem

### CODE REVIEW

**Review by chienandalu — COMMENTED** [review]
Why not adpating delivery packages (stock.quant.package) to pos? Isn't it the same concept?

**Comment by legalsylvain** [comment]
Hi @remytms thanks a lot for sharing this module.
There are pending work regarding pos_tare module on [9.0](https://github.com/OCA/pos/pull/470) and [12.0](https://github.com/OCA/pos/pull/491).
V12.0 is quasi ready to review. (some little things to fix with @Fkawala)

It includes part of the feature of your module. (mainly the computation of net and gross weight and the ``tare`` field on ``pos.order.line``)

My proposal is to make your module ``pos_container`` depend on ``pos_tare`` to add the extra feature of containers.

In the other part, I abstain regarding @chienandalu remarks.

thanks !

**Comment by legalsylvain** [comment]
any news regarding @chienandalu remarks and mines ? 

thanks !

**Comment by robinkeunen** [comment]
@chienandalu that decision dates a bit but, to the best of my memories, we wanted a simple object for tracking the weight of the customers containers while `stock.quant.package` deals with various type of packaging you have in stock (carton packaging of size x, carton packaging of size y, pallets, ...). 

I think we were also a bit afraid of  the `stock.quant.package` model...

**Comment by legalsylvain** [comment]
Thanks a lot Robin. And did you take a look on pos_tare module ? (Now merged in v12)

**Comment by robinkeunen** [comment]
No, I have not, @vvrossem was following this but he's on sick leave until septembre. I won't have time to look at it in the near future... :/

**Comment by carmenbianca** [comment]
@remytms @robinkeunen this PR is still used by us, but has been closed for half a year.

**Pull request closed without merging**
