### PR TITLE
12.0 mig pos report session summary

### PR DESCRIPTION
**Pull request by wpichler**

### CODE REVIEW

**Review by chienandalu — COMMENTED** [review]
Wasn't the original one a backport of later Odoo core features?

**Comment by wpichler** [comment]
The original one was in odoo v9 (https://github.com/odoo/odoo/blob/9.0/addons/point_of_sale/views/report_sessionsummary.xml) - was removed in odoo v10. So it went into oca/pos

**Review by PierrickBrun — APPROVED** [review]

**Review by legalsylvain — APPROVED** [review]
Tested on runbot. Works perfectly. Thanks.

**Pull request merged**
