### PR TITLE
[16.0][ADD] pos_screen_element_custom_size

### PR DESCRIPTION
**Pull request by geomer198**
This module allows to define custom size values for certain POS screen elements.

### CODE REVIEW

**Review by legalsylvain — CHANGES_REQUESTED** [review]
Interesting module. thanks for sharing ! 
could you remove the pandoc... .deb file ? 

thanks !

**Comment by geomer198** [comment]
> Interesting module. thanks for sharing ! could you remove the pandoc... .deb file ?
> 
> thanks !

Could you check again?

**Comment by cvinh** [comment]
> > Interesting module. thanks for sharing ! could you remove the pandoc... .deb file ?
> > thanks !
> 
> Could you check again?

Do you have any idea how the pandoc deb appeared ? I had the same in one of my PR once...

**Comment by geomer198** [comment]
> > > Interesting module. thanks for sharing ! could you remove the pandoc... .deb file ?
> > > thanks !
> > 
> > 
> > Could you check again?
> 
> Do you have any idea how the pandoc deb appeared ? I had the same in one of my PR once...

Pandoc is added after running pre-commit.

**Review by ivs-cetmix — APPROVED** [review]
Functional review LGTM
@legalsylvain would appreciate your code review when you have time)

**Review by legalsylvain — APPROVED** [review]
Code review no test. LGTM.

Note : could be great to have also a min height. when product has no images, the button can be too little. 

image


not a blocking point, can be added later.

**Comment by legalsylvain** [comment]
Hi @geomer198 could you rebase and take a look on red ci ? Thanks !

**Comment by ivs-cetmix** [comment]
hi @legalsylvain could you please check again? Thank you in advance!

**Comment by legalsylvain** [comment]
HI @OCA/pos-maintainers. we have regularly a weird error on OCA/pos CI. Description : 
- The PR is green (all checks are OK)
- we call ocabot
- the merge of ocabot fails.
- when we check the errors, there is an error on OCB, meanwhile odoo is green.

image

- finally after many tries, it works. (without any code change, or any rebase).

Do you have an idea on how to solve the problem ? 

thanks ! cc @ivantodorovich

**Comment by ivantodorovich** [comment]
Indeed, I've seen it too. I'll try to investigate in the coming days.
It's always related to the `pos_order_to_sale_order` module, isn't it?

```
2024-05-10 14:45:44,264 397 ERROR odoo odoo.addons.pos_order_to_sale_order.tests.test_module: FAIL: TestUi.test_pos_order_to_sale_order
Traceback (most recent call last):
  File "/__w/pos/pos/pos_order_to_sale_order/tests/test_module.py", line 36, in test_pos_order_to_sale_order
    self.assertEqual(len(before_orders) + 1, len(after_orders))
AssertionError: 1 != 0
```

**Comment by ivantodorovich** [comment]
fix proposed here:
- https://github.com/OCA/pos/pull/1211

**Pull request merged**
