### PR TITLE
12.0 fix pos order return

### PR DESCRIPTION
**Pull request by ajayjaviya**
Issue 1:Pos order partial return gives wrong total
When create a partial pos order return amount total on return order is always copy from the original order

pos_order_wrong_total

Issue 2: pos order return module is not working with `l10n_fr_pos_cert`

If `l10n_fr_pos_cert`  is installed user can not return pos order if order is Invoiced or Posted AND the company's country code falls in any of ['FR', 'MF', 'MQ', 'NC', 'PF', 'RE', 'GF', 'GP', 'TF'].
pos_order_return

### CODE REVIEW

**Comment by ajayjaviya** [comment]
@ivantodorovich : can you please review this PR

**Review by legalsylvain — APPROVED** [review]
Hi @ajayjaviya. Thanks for this patch. 
regarding the first point (wrong total). LGTM
regarding the second point, I don't understand why your last commit is fixing something. (not a blocking point, just to understand).

thanks !

**Review by ivantodorovich — APPROVED** [review]

**Comment by ivantodorovich** [comment]
@legalsylvain to answer on point 2:

When calling `copy()` without setting a new value for `order_id`, it triggers this constraint:
https://github.com/odoo/odoo/blob/12.0/addons/l10n_fr_pos_cert/models/pos.py#L195

**Comment by legalsylvain** [comment]
> When calling copy() without setting a new value for order_id, it triggers this constraint:
https://github.com/odoo/odoo/blob/12.0/addons/l10n_fr_pos_cert/models/pos.py#L195

Copying an object make a write on the copied object ? I don't understand why.

OK. then. Thanks for the answer !

**Comment by ivantodorovich** [comment]
Well.. now that you mention this, no.
In fact what's happening is that the following write triggers the constraint with the previous order_id value, because super() is called at the very end https://github.com/odoo/odoo/blob/12.0/addons/l10n_fr_pos_cert/models/pos.py#L196

**Comment by ivantodorovich** [comment]
@legalsylvain can we merge this one? :)

**Comment by legalsylvain** [comment]
Sure !
/ocabot merge patch

**Pull request merged**
