### PR TITLE
[NEW] Module that links the pos order with it respective picking

### PR DESCRIPTION
**Pull request by sadamo**

### CODE REVIEW

**Comment by rvalyi** [comment]
looks good but some style errors, see in the Travis build..,

**Comment by legalsylvain** [comment]
Hi @sadamo, 

thanks for this module. could you fix this 4 travis error ? 
https://travis-ci.org/OCA/pos/jobs/152845382#L455

thanks.
regards.

**Comment by sadamo** [comment]
Fixed PEP8

**Comment by legalsylvain** [comment]
LGTM. Thanks !
(code review + test).
@rvalyi, could you take a look ?

**Review by rafaelbn — APPROVED** [review]
Tested in runbot

**Comment by rafaelbn** [comment]
Hi @legalsylvain @sadamo I've merge this PR which is code+test OK but I think I mistake because it needed a rebase before merging... so I revert it.

**Comment by pedrobaeza** [comment]
If you was able to merge, no need to rebase. Rebase has 2 purposes:

* Have in PR latest changes from upstream branch, so tests or errors can be cleared.
* Avoid conflicts merging.

**Pull request merged**
