### PR TITLE
Modify to V15

### PR DESCRIPTION
**Pull request by ghost**
Modify this module to v15

### CODE REVIEW

**Comment by nuprod** [comment]
Hello I can't understand why it's not working ?

**Comment by renzyndrome** [comment]
> Hello I can't understand why it's not working ?

hello, can you make it work now?

**Comment by nuprod** [comment]
Hello same error on pre commit
--- a/pos_order_remove_line/__manifest__.py
+++ b/pos_order_remove_line/__manifest__.py
@@ -8,16 +8,16 @@
     "website": "https://github.com/OCA/pos",
     "category": "Point of Sale",
     "maintainers": ["robyf70"],
-    'version': '15.0.1.0.1',
+    "version": "15.0.1.0.1",
     "license": "LGPL-3",
     "depends": ["point_of_sale"],
-    'assets': {
-        'point_of_sale.assets': [
-            '/pos_order_remove_line/static/src/css/orderline.scss',
-            '/pos_order_remove_line/static/src/js/orderline.js',
+    "assets": {
+        "point_of_sale.assets": [
+            "/pos_order_remove_line/static/src/css/orderline.scss",
+            "/pos_order_remove_line/static/src/js/orderline.js",
         ],
-        'web.assets_qweb': [
-            '/pos_order_remove_line/static/src/xml/*',
+        "web.assets_qweb": [
+            "/pos_order_remove_line/static/src/xml/*",
         ],
     },
 }
diff --git a/pos_order_remove_line/readme/CONTRIBUTORS.rst b/pos_order_remove_line/readme/CONTRIBUTORS.rst
index [155](https://github.com/OCA/pos/actions/runs/3143267537/jobs/5107807417#step:7:156)da5f..db1fd3e 100644
--- a/pos_order_remove_line/readme/CONTRIBUTORS.rst
+++ b/pos_order_remove_line/readme/CONTRIBUTORS.rst
@@ -1,4 +1,4 @@
 * Roberto Fichera <roberto.fichera@levelprime.com>
 * Iván Todorovich <ivan.todorovich@gmail.com>
 * Foram Shah <foram.shah@initos.com>
-* Romain Frucco <romain.frucco@nuprod.fr>
\ No newline at end of file
+* Romain Frucco <romain.frucco@nuprod.fr>
Error: Process completed with exit code 1.

**Comment by nuprod** [comment]
@renzyndrome Hello still need help pre-commit it's not working

**Pull request closed without merging**
