### PR TITLE
[16.0][MIG] pos_edit_order_line: Migration to 16.0

### PR DESCRIPTION
**Pull request by FrancoMaxime**

### CODE REVIEW

**Comment by flachica** [comment]
Dear @FrancoMaxime. I made this [PR](https://github.com/OCA/pos/pull/926) to migrate this module. Please, could you review it in order to make only one PR? Thanks

**Comment by FrancoMaxime** [comment]
@flachica Oh, my bad, I missed it. I'll do it now

**Review by baimont — APPROVED** [review]
Functional test ok
Code LGTM, just pre-commit to fix

**Review by flachica — APPROVED** [review]

**Review by apineux — APPROVED** [review]

**Review by ivantodorovich — APPROVED** [review]
Technical review : LG

**Pull request merged**
