### PR TITLE
[14.0][MIG] pos_order_to_sale_order: Migration to 14.0

### PR DESCRIPTION
**Pull request by zamberjo**

### CODE REVIEW

**Review by chienandalu — COMMENTED** [review]
Thanks for this @zamberjo :+1: 

A tiny functional issue I found is that when you convert the pos order to sale order it isn't flushed from the PoS order list, so they remain there until manually removed. May you have to destroy it.

**Comment by belenaures** [comment]
Tested and found that everything works correctly. It is true that as for the orders created (as [chienandalu] says), could be deleted from the PoS order list once they have been created.

**Comment by zamberjo** [comment]
hi  @chienandalu @belenaures  done, now the order is removed from the list once the sale.order is created

**Review by chienandalu — APPROVED** [review]
Thanks! :+1:

**Comment by chienandalu** [comment]
@belenaures add a proper Github approval

**Review by belenaures — APPROVED** [review]
LGTM

**Comment by zamberjo** [comment]
Hi @pedrobaeza Can you check it?

**Pull request merged**
