### PR TITLE
[FIX] Bug on pos_access_right: black screen when opening POS

### PR DESCRIPTION
**Pull request by regaby**
This pull request closes this issue: https://github.com/OCA/pos/issues/223

### CODE REVIEW

**Review by chienandalu — COMMENTED** [review]
Thanks @regaby Check lint as it seems to be failing

**Comment by regaby** [comment]
Hi @chienandalu , i fixed the syntax in the module pos_access_right with lint. But it's seems like the other modules in the repository are not validating that.

**Review by chienandalu — COMMENTED** [review]
Hi, @regaby Rebase your branch to get the last CI fixes

**Comment by legalsylvain** [comment]
@regaby  could you rebase ?

**Comment by rousseldenis** [comment]
@legalsylvain

**Comment by houssine78** [comment]
ping @legalsylvain  ;)

**Pull request merged**
