### PR TITLE
13.0 mig pos payment method image

### PR DESCRIPTION
**Pull request by hitrosol**
PR with commit history as replacement of #638, since it error due to changing in the pos_empty_home

### CODE REVIEW

**Review by ivantodorovich — APPROVED** [review]
I'm not sure I understand why we need the new PR (instead of rebasing / updaing the previous one)

But in any case, LGTM :+1:

Can you close the previous PR, if it's not used anymore?

**Comment by hitrosol** [comment]
@ivantodorovich, I have closed the previous one, thanks for your approval. 
Can you guide me how to proceed so this can be merged ?

**Comment by ivantodorovich** [comment]
> @ivantodorovich, I have closed the previous one, thanks for your approval.
> Can you guide me how to proceed so this can be merged ?

Well, to get a PR merged you need at least two approvals + someone from the repository team to trigger the merge after.

This is all based on collaboration, so a general rule of thumb is that you review at least 2 other PRs (give 2 reviews, receive 2 reviews). This of course doesn't guarantee your PR will receive immediate reviews, but it's what keeps the system going.

**Comment by hitrosol** [comment]
Thanks @ivantodorovich. I'm still learning to collaborate in OCA, I'll learn from other PR and start to review them.
Hi @brendapaniagua, as you have approved the similar PR in #638, hopefully you can approve this one as well.

**Comment by bunhin** [comment]
I try the functional on runbot:
go to point of sale menu, clik on configuration, click on payment method, select cash and click edit, image placeholder shown, add image by select from local folder then save. Repeat for other payment method. --> ok
open pos session, create order with discount -->add customer and set customer --> ok
Then click payment (image shown in on the payment methode which i add the image above) --> ok
select one payment method and set the amount (partial) ---> ok
select other payment method and set the balance amount --->ok
validate order ---> ok
print receipt ---> ok.

I believe it is all ok

LGTM

**Comment by legalsylvain** [comment]
thanks for porting this module. 

/ocabot merge patch

**Pull request merged**
