### PR TITLE
[WIP][14.0][mig] pos_product_template

### PR DESCRIPTION
**Pull request by hparfr**
Migration of pos_product_template. 

The only last stable version was from v10. I cherry picked the interesting commit from v11 or v12 port tentative.

Because of a different object model of attributes and "owl" js, a lot of refactorings were needed.

It now works with created variants. pos_fix_search_limit dependency has been dropped.

Current status: it's usable, but the code quality is poor.
For sure, the CSS and js code need still a lot of work before the merge.

I hope to have to work on it in Jan or Feb 2021.

### CODE REVIEW

**Comment by ivantodorovich** [comment]
Hello!
Is this still WIP or is it ready?

**Comment by pedroguirao** [comment]
Hello,

There is someone  working on this?

On "select variant" popup we are able to select more than one attribute, and we think the correct solution would be select only one. We can work on it if nobody is already.


Best regards!

**Comment by antoniocanovas** [comment]
Hello,
I think  a good option for ui could be like standard pos configurator v14 (with radio and select options defined on attributes).

It could be homogeneous with standard when product template has attributes with variants creation "always" and  "never" (and pos configurator option is active). The system asks first for "always" and later for the "never" ones with the same UI.

WDYT?

**Comment by sebastienbeau** [comment]
Hi I just merged some improvement and now we will have time for processing feedback, can you try it ?
@PierrickBrun can you follow-up this PR to process feedback ? Thanks

**Comment by antoniocanovas** [comment]
Hi, thanks.
We finished this module weeks ago and we were pending of PR upload.
I will talk with @pedroguirao to share.

**Comment by pedroguirao** [comment]
Hi all , after checking the PR we think the module has some changes about the original funcionality, we did this PR wich works as originaly intended. PR #750

**Comment by elvise** [comment]
> Hi all , after checking the PR we think the module has some changes about the original funcionality, we did this PR wich works as originaly intended. PR #750

@pedroguirao can we close this PR ?

**Comment by pedroguirao** [comment]
> > Hi all , after checking the PR we think the module has some changes about the original funcionality, we did this PR wich works as originaly intended. PR #750
> 
> @pedroguirao can we close this PR ?

Hi @elvise , sorry for the delay i was a bit busy for the last weeks, you refer closing the #571 or #750 ?

**Comment by elvise** [comment]
> > > Hi all , after checking the PR we think the module has some changes about the original funcionality, we did this PR wich works as originaly intended. PR #750
> > 
> > 
> > @pedroguirao can we close this PR ?
> 
> Hi @elvise , sorry for the delay i was a bit busy for the last weeks, you refer closing the #571 or #750 ?

Hi @pedroguirao  np :) I’m talking about #571 as i understood this PR is in stale and we are moving to #750 am i right ?

**Comment by pedroguirao** [comment]
Yes the one to be merge as fas as i know will be #750 :)

**Comment by mileo** [comment]
Already merged... can some one close it?

**Pull request closed without merging**
