### PR TITLE
[FIX] BUG #57 that does not allow to create fields in the UI.

### PR DESCRIPTION
**Pull request by carlosrve**
This fixes bug #57.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please check pylint errors.

**Comment by andhit-r** [comment]
@cv-clearcorp functional test ok. waiting for green travis.

**Comment by carlosrve** [comment]
@pedrobaeza OK, where good for the travis test.

**Review by pedrobaeza — APPROVED** [review]
Thanks for the changes. Fast-tracking this.

**Comment by carlosrve** [comment]
@pedrobaeza thanks, always happy to help.

**Pull request merged**
