### PR TITLE
[FIX] add pos_fix_search_limit dependency 

### PR DESCRIPTION
**Pull request by mourad-ehm**
add pos_fix_search_limit dependency to fix template lacking bug if more than 100 variants.
@hparfr

### CODE REVIEW

**Review by hparfr — APPROVED** [review]
Thanks @mourad-ehm

**Review by legalsylvain — APPROVED** [review]
Makes sense. not tested. :+1: 
thanks @mourad-ehm !

**Comment by mourad-ehm** [comment]
ping @bealdav @chafique-delli could you review this PR ?

**Review by chafique-delli — APPROVED** [review]
It's ok for me.

**Comment by pedrobaeza** [comment]
I don't see correct to add a new dependency in a stable module. This will break all the existing installations that don't have this module installed. You can add a recommendation of installing that module, but not to force it.

**Comment by pedrobaeza** [comment]
@legalsylvain you have merged while I was writing previous comment...

**Comment by legalsylvain** [comment]
image

Yes. concurrent work.

@pedrobaeza : what about to increment revision of this module ? It should fix the problem, don't you think ?

**Comment by pedrobaeza** [comment]
I'm afraid not. Take into account the following scenario:

- You have previous version of `pos_product_template`.
- You don't have `pos_fix_search_limit` installed.
- Update code for your repositories.
- Service restarted.
- `pos_product_template` module won't be loaded because there's an unresolved dependency.
- It's not auto-installed even in the case you have the module accessible on your addons path.

**Comment by hparfr** [comment]
Increment the major version number allows to introduce breaking changes, isn't it ?

**Comment by legalsylvain** [comment]
> - Update code for your repositories.
> - Service restarted.

Yes, this is because a step is missing. When restarting, you should ``-u modules``. (at least, the modules where the code changed, or ``-u all`` otherwise). If you don't want to ``-u``, you should not update your code. It will fail a lot of time. (if a xml file is added or updated for exemple)

I tested, and it works correctly. If I add uninstalled ``module_A`` as a dependence of ``module_B`` that is installed, and if I do ``-u module_B``, it will install ``module_A``

I understand you that maybe some production environment that doesn't deploy correctly will fail but there is a bug, that make the module quite unusable, and this dependency fix it. So it's important.

**Comment by legalsylvain** [comment]
> Increment the major version number allows to introduce breaking changes, isn't it ?

I'm not very clear on that point. For me it's "informational" changes. And also I think that if you change the version number, Odoo will propose you to update the code, via the UI. (but I don't use this feature)

**Comment by pedrobaeza** [comment]
@legalsylvain with regular Odoo (not OpenUpgrade), AFAIK, updating a module with a dependency not installed doesn't install that dependency. Are you sure about this?

About correctly deployed, it's also interpretable, as I deploy my systems correctly, but limiting the exposed addons for avoiding possible side effects or limiting customer actions installing not covered modules.

**Comment by legalsylvain** [comment]
> @legalsylvain with regular Odoo (not OpenUpgrade), AFAIK, updating a module with a dependency not installed doesn't install that dependency. Are you sure about this?

Just tested on a 8.0, based on OCA/OCB. and yes. Maybe not in more recent version.

> About correctly deployed, it's also interpretable, as I deploy my systems correctly, but limiting the exposed addons for avoiding possible side effects or limiting customer actions installing not covered modules.

It was not a critic ! I do sometimes the same for any good reasons ! but yes, I think that if we pull code, we should update code. (that is the objective of the module from acsone that check if code changed, doesn't it ?)
regards.

**Comment by pedrobaeza** [comment]
Hehe, yes, it was more our module and upgraded by Acsone, but we detected that need and do it in first place in collaboration with LasLabs :wink: 

I'm pretty sure in v10 auto-install is not happening, but hey, I won't fight anymore as I'm not a user of this myself and I don't want to be always the nitpicking man.

**Comment by legalsylvain** [comment]
> Hehe, yes, it was more our module and upgraded by Acsone

sorry, my bad ! 

> I'm pretty sure in v10 auto-install is not happening, but hey, I won't fight anymore as I'm not a user of this myself and I don't want to be always the nitpicking man.

Just tested in a fresh database with point_of_sale installed. (OCA/OCB/10.0)
- add a dependency in ``point_of_sale`` to ``crm``
- restart, with ``-u point_of_sale``
- ``crm`` is installed

**Comment by pedrobaeza** [comment]
OK, great, then I should change my assumptions about this.

**Pull request merged**
