### PR TITLE
[10.0][MIG] pos_order_mgmt backport

### PR DESCRIPTION
**Pull request by robyf70**
Just a backport of the module

### CODE REVIEW

**Review by legalsylvain — CHANGES_REQUESTED** [review]
Thanks a lot for your contribution. 

LGTM for me. (Code review / no test)

Could you check travis ? Tests of the module are failing.

Kind regards.

**Comment by robyf70** [comment]
> Thanks a lot for your contribution.
> 
> LGTM for me. (Code review / no test)
> 
> Could you check travis ? Tests of the module are failing.
> 
> Kind regards.

Thanks for reviewing the module. I've fixed the test issue and now travis is happy!

**Review by chienandalu — CHANGES_REQUESTED** [review]
Keep in mind this bug I solved in v11 and I just put in PR to FW port to v12 in https://github.com/OCA/pos/pull/417

**Comment by robyf70** [comment]
> Keep in mind this bug I solved in v11 and I just put in PR to FW port to v12 in #417

I will have a look right now

**Comment by robyf70** [comment]
@chienandalu Just pushed the changes including #417

**Review by eLBati — CHANGES_REQUESTED** [review]
pos.config form needs fixing:

image

Other tests are OK

**Comment by robyf70** [comment]
@eLBati I've reviewed the ``pos.config`` view, now should be ok

**Review by eLBati — APPROVED** [review]
Thanks

**Review by chienandalu — APPROVED** [review]
Thanks! :+1:

**Pull request merged**
