### PR TITLE
[9.0][MIG] pos_payment_terminal: Backport from 10.0

### PR DESCRIPTION
**Pull request by rousseldenis**
* Backport from 10.0
* Embed #245

### CODE REVIEW

**Comment by rafaelbn** [comment]
We have here missing a CLA cc @invitu

**Comment by cvinh** [comment]
I changed my github username from 'invitu' to 'cvinh' months ago... I signed a new CLA so 'invitu' is not CLA anymore...
Do I have to rebase somewhere ?

**Comment by rafaelbn** [comment]
Hi @azmeuk please could you review this PR?

**Comment by rafaelbn** [comment]
Here we have a backport of pos_payment_terminal from 10.0 to 9.0 but here https://github.com/OCA/pos/pull/388 we have a FIX of pos_payment_terminal courtesy of @azmeuk :thinking:

**Review by rafaelbn — APPROVED** [review]
:+1:

**Comment by rousseldenis** [comment]
I've changed button disposition to be more extensible.

If for some reasons, pos_mercury is installed and you try to install another module depending on this one, the dependency order makes button disappear (pos_mercury replaces the payment line name column in template)

**Comment by rousseldenis** [comment]
Just updated from 10.0 last changes.

I've created a hook to prepare transaction data.

**Comment by rousseldenis** [comment]
I need to fix some code because of new/old api problems.

**Comment by rousseldenis** [comment]
Done

**Comment by rousseldenis** [comment]
@azmeuk This one is ready.
@legalsylvain

**Comment by azmeuk** [comment]
This looks good to me, but I am not a reviewer :)

**Comment by legalsylvain** [comment]
hi @azmeuk : all people can review OCA pull request. no need to be part of the association.

You just have to click on "file changed" then "Review changes" and tip your text and approve (or not). If you make a functional review or a code review, or both, mention it.

thanks.

**Review by legalsylvain — APPROVED** [review]
LGTM. Thanks. (code review / no test.)

**Review by azmeuk — APPROVED** [review]

**Comment by legalsylvain** [comment]
Thanks.
/ocabot merge

**Pull request merged**
