### PR TITLE
[16.0][IMP] pos_order_to_sale_order

### PR DESCRIPTION
**Pull request by geomer198**
Code is refactored and tests are updated.

### CODE REVIEW

**Comment by geomer198** [comment]
@legalsylvain Could you check changes?

**Review by legalsylvain — APPROVED** [review]
thanks for improving code and tests.

One queston : why did you added ``msg=xxx`` in tests ?

**Comment by geomer198** [comment]
> thanks for improving code and tests.
> 
> One queston : why did you added `msg=xxx` in tests ?

I'm used to writing like that.

**Review by angelinaanaki — APPROVED** [review]
LGTM

**Review by danielduqma — APPROVED** [review]

**Review by legalsylvain — COMMENTED** [review]
/ocabot merge patch

**Pull request merged**
