### PR TITLE
[16.0][MIG] pos_order_line_no_unlink

### PR DESCRIPTION
**Pull request by legalsylvain**
Port trivial module that fixes a bug in Odoo, that allows user to unlink pos order lines of confirmed / invoiced orders.

CC : @carmenbianca This one could interest you.

### CODE REVIEW

**Comment by rafaelbn** [comment]
Hello @legalsylvain ! Is there an issue opened to Odoo? I mean, if Odoo fix it is better than a new module. Isn't it? I understand why but imagine we fix with modules all the issues of Odoo 😜. Just comment not blocking at all! I agree 👍🏼 is a BUG

**Comment by legalsylvain** [comment]
@mart-e : interested by a PR on that topic ? 
regards.

**Review by carmenbianca — APPROVED** [review]
LGTM. But like remarked, this should probably be an issue/PR against Odoo upstream.

Let's first see if Odoo recognises this as a bug. If they don't, we can merge this.

**Comment by legalsylvain** [comment]
thanks to your review.

Done here https://github.com/odoo/odoo/pull/119777

Let's see if it goes through !

regards.

**Comment by mart-e** [comment]
> interested by a PR on that topic ?
regards.

I don't work in the pos team so I can't answer if this is considered as a bug but I see they have been pinged via codeowner of the odoo/odoo PR so will see 🤞

**Review by enriquemartin — APPROVED** [review]

**Review by FrancoMaxime — APPROVED** [review]

**Comment by rafaelbn** [comment]
> Hello @legalsylvain ! Is there an issue opened to Odoo? I mean, if Odoo fix it is better than a new module. Isn't it? I understand why but imagine we fix with modules all the issues of Odoo 😜. Just comment not blocking at all! I agree 👍🏼 is a BUG

@legalsylvain 😄 we got something!

> Description of the issue/feature this PR addresses:
> •	create a custom view by UI to display pos.order.line
> •	select some pos.order lines (related to paid orders)
> •	click on unlink
> Current behavior before PR:
> •	the pos.order.lines are deleted.
> Desired behavior after PR is merged:
> •	A blocking error is displayed.
> Note : this patch is a "should have" for Odoo Point of Sale, and a "must have" if french certification is installed. (otherwise, the certification chain is broken).
> CC : @rafaelbn, @carmenbianca
> closes: https://github.com/OCA/pos/pull/989
> Forward-Port-Of: https://github.com/odoo/odoo/pull/119777
> ________________________________________
> You can view, comment on, or merge this pull request online at:
>   https://github.com/odoo/odoo/pull/126558
> Commit Summary
> •	[bc40e6a](https://github.com/odoo/odoo/pull/126558/commits/bc40e6ada8a8d44d3344e817e1c49dd2f454cae8) [FIX] point_of_sale : prevent to unlink pos.order.line related to 'paid' / 'invoiced' order.
> File Changes

**Review by rafaelbn — APPROVED** [review]

**Comment by legalsylvain** [comment]
Indeed. Closing as bug fixed in V16

**Pull request closed without merging**
