### PR TITLE
[MIG] 12.0 mig pos fix search limit

### PR DESCRIPTION
**Pull request by cvinh**

### CODE REVIEW

**Review by chienandalu — CHANGES_REQUESTED** [review]
Please, review travis errors :wink:

**Comment by cvinh** [comment]
> Please, review travis errors

@chienandalu I don't understand Travis errors `The command "sh -e /etc/init.d/xvfb start" failed and exited with 127 during`

**Comment by pedrobaeza** [comment]
Please rebase in latest 12.0

**Comment by cvinh** [comment]
> Please rebase in latest 12.0

Travis error is still here with 12.0

**Comment by pedrobaeza** [comment]
Right, update main branch. Try now.

**Review by legalsylvain — CHANGES_REQUESTED** [review]
Hi @cvinh. Thanks for porting this module. 
could you fix lint noices, present in Travis, regarding Javascript ?

https://travis-ci.org/OCA/pos/jobs/531934872#L330

Help available here : https://github.com/OCA/pos/wiki
ref (https://github.com/OCA/pos/pull/369)

**Comment by rafaelbn** [comment]
Hi @cvinh , can you read review and attend them please? There are some tips for you. Thanks

**Pull request closed without merging**
