### PR TITLE
[17.0][ADD] pos_partner_address_required: New module pos_partner_address_required

### PR DESCRIPTION
**Pull request by peluko00**
The module put the different fields of address required on POS partner view.

cc https://github.com/APSL 161148
@miquelalzanillas @lbarry-apsl @javierobcn @mpascuall @BernatObrador @ppyczko please review

### CODE REVIEW

**Review by mpascuall — APPROVED** [review]
LGTM, tested in runboat

**Review by BernatObrador — APPROVED** [review]
LGMT!

**Review by ppyczko — APPROVED** [review]
LGTM, tested in runboat

**Comment by peluko00** [comment]
Hi @ivantodorovich, could you review please. Thanks!

**Review by ivantodorovich — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
