### PR TITLE
[16.0][FIX]pos_order_remove_line: Action on trash delete line

### PR DESCRIPTION
**Pull request by DorianMAG**
Change javascript method to delete a line when click on the trash

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]
Lgtm.

**Review by flotho — APPROVED** [review]
LGTM

**Comment by flotho** [comment]
pop @DorianMAG please correct the pre commit

**Comment by DorianMAG** [comment]
> pop @DorianMAG please correct the pre commit

Dont understand why pre-commit failed.
Xml file look good

**Comment by JulienMartinez** [comment]
LGTM

**Comment by DorianMAG** [comment]
> pop @DorianMAG please correct the pre commit

Finally understand, semicolon less in javascript file.
Thx for the help
Regards

**Review by flotho — APPROVED** [review]
this module is not concerned by the test failure.
LGTM

**Review by robyf70 — APPROVED** [review]
LGTM

**Comment by DorianMAG** [comment]
@robyf70 
Odoo test failed on pos_order_to_sale_order module.
Any idea to fix the problem?
Regards

**Comment by robyf70** [comment]
> @robyf70 Odoo test failed on pos_order_to_sale_order module. Any idea to fix the problem? Regards

No idea how to fix it

**Comment by DorianMAG** [comment]
@robyf70 
All tests passed in PR.
Can you retry the merge plz.
Regards

**Comment by robyf70** [comment]
> @robyf70 Odoo test failed on pos_order_to_sale_order module. Any idea to fix the problem? Regards

@legalsylvain Can you please look at this error?

```
2024-01-05 09:04:36,584 339 ERROR odoo odoo.addons.pos_order_to_sale_order.tests.test_module: FAIL: TestUi.test_pos_order_to_sale_order
Traceback (most recent call last):
  File "/__w/pos/pos/pos_order_to_sale_order/tests/test_module.py", line 36, in test_pos_order_to_sale_order
    self.assertEqual(len(before_orders) + 1, len(after_orders))
AssertionError: 1 != 0
 ```

**Comment by robyf70** [comment]
> /ocabot merge minor

Let's try

**Comment by legalsylvain** [comment]
> @legalsylvain Can you please look at this error?

No time to investigate. indeed, something look broken in V16 branch. however, I just tested pos_order_to_sale_order solo, and it works. So I guess that it is an incompatibility with other module(s)
I can take a look in a few weeks.

**Review by chienandalu — CHANGES_REQUESTED** [review]
This shouldn't be merged as it is:

- The commits should be squashed into a single one
- The commit message should have a proper description, that contains a tag, the module name and the essence of the change e.g.: "[FIX] pos_order_remove_line: trash action"
- There are unnecessary changes in spacings

**Comment by DorianMAG** [comment]
> > @robyf70 Odoo test failed on pos_order_to_sale_order module. Any idea to fix the problem? Regards
> 
> @legalsylvain Can you please look at this error?
> 
> ```
> 2024-01-05 09:04:36,584 339 ERROR odoo odoo.addons.pos_order_to_sale_order.tests.test_module: FAIL: TestUi.test_pos_order_to_sale_order
> Traceback (most recent call last):
>   File "/__w/pos/pos/pos_order_to_sale_order/tests/test_module.py", line 36, in test_pos_order_to_sale_order
>     self.assertEqual(len(before_orders) + 1, len(after_orders))
> AssertionError: 1 != 0
> ```
Hi @legalsylvain 
Thx, i take a look

**Comment by DorianMAG** [comment]
> This shouldn't be merged as it is:
> 
>     * The commits should be squashed into a single one
> 
>     * The commit message should have a proper description, that contains a tag, the module name and the essence of the change e.g.: "[FIX] pos_order_remove_line: trash action"
> 
>     * There are unnecessary changes in spacings

Thx, i take a look for commit recomandation.
spacings changes was come from pre-commit, the original code did not have the correct indent

**Comment by DorianMAG** [comment]
> This shouldn't be merged as it is:
> 
>     * The commits should be squashed into a single one
> 
>     * The commit message should have a proper description, that contains a tag, the module name and the essence of the change e.g.: "[FIX] pos_order_remove_line: trash action"
> 
>     * There are unnecessary changes in spacings

It's done,
Regards

**Review by JulienMartinez — APPROVED** [review]
LGTM

**Comment by danielduqma** [comment]
Hi @DorianMAG,

These changes revert some fixes made in https://github.com/OCA/pos/pull/1044. I checked it on [runboat](http://oca-pos-16-0-pr1120-893fe4e62b04.runboat.odoo-community.org/), having `pos_loyalty` installed:
1. Select a customer
2. Add a product to cart
3. Add another different product to cart
4. Remove last line
5. Loyalty points balance hasn't changed

cc @papulo79

**Comment by papulo79** [comment]
Hi @DorianMAG,

I've repeat the process described by @danielduqma and I had the same results.

This MR has broken the module with pos loyalty.

@robyf70

**Comment by DorianMAG** [comment]
@papulo79 @danielduqma 
Manifestly, the entire order is updated, except loyalty.
I will take a look

**Comment by ivantodorovich** [comment]
@DorianMAG I take from the last comments that this PR is still not ready yet?

**Comment by DorianMAG** [comment]
> @DorianMAG I take from the last comments that this PR is still not ready yet?

Hi,
indeed, i need to find a solution.
I try to find time this week to fix that.

but this one is ok
https://github.com/OCA/pos/pull/1122

**Pull request closed without merging**
