### PR TITLE
[MIG][9.0]Updated pos_product_template addon to 9.0

### PR DESCRIPTION
**Pull request by navarromiguel**
I have updated the pos_product_template addon from 8.0 to 9.0 version and added spanish translation. I tested it and works.

### CODE REVIEW

**Comment by fescon** [comment]
I got an "warning: Some modules could not be started Missing dependencies:   ["point_of_sale.screens", "point_of_sale.popups", "point_of_sale.models", "point_of_sale.chrome", "point_of_sale.gui", "point_of_sale.DB", "point_of_sale.BaseWidget"] Error in console

**Comment by fescon** [comment]
the warning was caued by a faulty deinstallation - BUT if a product has more than 100 Variants - which is not hard to reach in a restaurant - the product does not show up in POS!

**Comment by florca1979** [comment]
Module pos product template v9
Do not support scans of barcodes with readers

Some idea that may be failing, friends

**Comment by rafaelbn** [comment]
Hi @navarromiguel , thanks for this migration. Are you going to continue it? If so please:

- Review https://github.com/OCA/pos/pull/135, this PR fix a bug in the same module you are porting to v9
- Rebase this PR in order to check with the last changes in travis
- Ping me when done I will review it

Thanks!

**Comment by cvinh** [comment]
in `__openerp__.py,` it seems that version is still in 8.0.0.2.0 and installable tag is still to 'False'

**Comment by navarromiguel** [comment]
@invitu yes, sorry I didn't update that file.

**Comment by libreec** [comment]
@navarromiguel could you please update the __openerp__.py file and incluye the fix in #135 so we can merge this PR.

Do you need any help?.

Thanks a lot.

**Comment by navarromiguel** [comment]
Changed openerp.py version from 8 to 9. #135

**Comment by rafaelbn** [comment]
Hi, please @invitu @libreec could you review this PR ? I would be nice to have some mor modules migrated yo v9. Thanks!

**Comment by coodec** [comment]
Hi @rafaelbn  we reviewed this PR with @libreec and it's working fine.

I have it on production for more than 3 months.

**Comment by mslokhat** [comment]
Hi,
was testing the module : 
got this error while loading the POS session : 


Loading product.template

Cannot read property 'attribute_value_ids' of undefined
TypeError: Cannot read property 'attribute_value_ids' of undefined
    at OdooClass.PosDB.include.add_templates (http://xxx:8069/pos_product_template/static/src/js/ppt.js:468:48)
    at Object.model.loaded (http://xxx:8069/pos_product_template/static/src/js/ppt.js:539:26)
    at Object.<anonymous> (http://xxx:8069/point_of_sale/static/src/js/models.js:513:46)
    at Object.<anonymous> (http://xxxx:8069/web/static/lib/jquery/jquery.js:3276:89)
    at fire (http://xxxx:8069/web/static/lib/jquery/jquery.js:3119:58)
    at Object.self.fireWith [as resolveWith] (http://xxxx:8069/web/static/lib/jquery/jquery.js:3231:49)
    at Object.<anonymous> (http://xxxxx:8069/web/static/lib/jquery/jquery.js:3283:104)
    at fire (http://xxxxx:8069/web/static/lib/jquery/jquery.js:3119:58)
    at Object.self.fireWith [as resolveWith] (http://xxxx:8069/web/static/lib/jquery/jquery.js:3231:49)
    at Object.deferred.(anonymous function) (http://xxxx:8069/web/static/lib/jquery/jquery.js:3321:62)

**Comment by cvinh** [comment]
@navarromiguel could you merge https://github.com/navarromiguel/pos/pull/2 as fix for https://github.com/OCA/pos/pull/135 is included in it ?

**Comment by mslokhat** [comment]
i have seen the issue : 
when you install pos_cache module, the object this.product_by_id in function add_templates is empty 

var product = this.product_by_id[templates[i].product_variant_ids[j]];

**Comment by rafaelbn** [comment]
Hi @navarromiguel , it look @invitu has fix the issue of this PR for you. Could you review, accept in order to get this merge?

**Review by navarromiguel — COMMENTED** [review]
I closed accidentally the PR and I've reopened again so, now, I can't approve it because I am the owner and it looks like a PR of me.
I've enabled the option that allows maintainers to commit.

**Comment by hparfr** [comment]
Hi, plan to migrate this module in v10.

#135 is still open and not merged in v8.  Why should it block this PR?

**Comment by legalsylvain** [comment]
> #135 is still open and not merged in v8. Why should it block this PR?

well please talk directly on the PR. In the first sight, it seems that the PR is still WIP and some remarks unresolved. but feel free to finish this PR.

Regards.

**Comment by hparfr** [comment]
Migration to v10 is ready for reviews : https://github.com/OCA/pos/pull/266 
The issue mentioned before has been fixed here : https://github.com/OCA/pos/tree/10.0/pos_fix_search_limit

**Review by rafaelbn — COMMENTED** [review]
Runbot doesn't work

**Comment by rafaelbn** [comment]
Please @invitu @libreec @coodec could you use Github reviews check screenshot

**Review by rafaelbn — APPROVED** [review]
Thanks :+1:

**Pull request merged**
