### PR TITLE
[MIG] pos_receipt_hide_price: Migration to 16.0

### LINKED ISSUE #868: [14] pos_receipt_hide_price    is useless, it hides the price but shows vat
The aim of the module is to hide the price when me give a present. If you hide the price but you dont hide the 21% vat and the amount of vat, the person who recives the gift , can gues the value of the present

## Module
[14] pos_receipt_hide_price

## Describe the bug
it shows vat

## To Reproduce
14

1. install module
2. sell in pos
3. print the tiket

**Expected behavior**
no price no vat

### PR DESCRIPTION
**Pull request by danielduqma**
Migration of what was implemented for 14.0. This also fixes https://github.com/OCA/pos/issues/868

Related: #849

### CODE REVIEW

**Review by ivantodorovich — APPROVED** [review]

**Comment by danielduqma** [comment]
Rebased over https://github.com/OCA/pos/pull/882, merge should be OK now

**Pull request merged**
