### PR TITLE
[DOC]Appropriate readm for v16

### LINKED ISSUE #1115: [16.0]pos_payment_change change policy option not displayed
## Module
pos_payment_change

## Describe the bug
once the module is installed, whatever the country of the main company, the option is not displayed in the settings
Moreover the image in the readme looks inappropriate for a v16

## To Reproduce
**Affected versions**:

latest 

1. install the module
2. try to setup following readme instructions
image

### PR DESCRIPTION
**Pull request by flotho**
Better readme 
FIX #1115

ping @legalsylvain

### CODE REVIEW

**Comment by legalsylvain** [comment]
Hi. Thanks. Could you update also the screenshot ? (You said it was obsolète)
Thanks !

**Comment by flotho** [comment]
Hi @legalsylvain 
Thanks I've checked and actually the screen is good but the way to access to it was not correct.
The changes solve this latest part.

**Review by legalsylvain — APPROVED** [review]
/ocabot merge patch

**Comment by flotho** [comment]
Hi @legalsylvain , how can I help on this one ?

**Comment by legalsylvain** [comment]
V16 branch should be fixed. there is an error. PR are stucked. I didn't investigated.

**Comment by flotho** [comment]
ping @gaelTorrecillas @DorianMAG  @julienMartinez

**Comment by legalsylvain** [comment]
Let's retry.



/ocabot merge patch

**Pull request merged**
