### PR TITLE
[17.0][MIG] pos_order_to_sale_order

### PR DESCRIPTION
**Pull request by chaule97**

### CODE REVIEW

**Comment by victorvermot** [comment]
Tests are fixed in this pr https://github.com/OCA/pos/pull/1232

**Review by cyrilmanuel — APPROVED** [review]
LGTM but shall add the other pr to fix the test or add a kink here to specifiy that it's required for merge this one

**Review by Ricardoalso — APPROVED** [review]
Depends on https://github.com/OCA/pos/pull/1232 but otherwise LGTM

**Review by manuelcalerosolis — APPROVED** [review]

**Comment by chaule97** [comment]
Hi @ivantodorovich, I fixed the issue, would you mind calling the merge bot again?

**Comment by ivantodorovich** [comment]
Thanks :) 

/ocabot merge nobump

**Pull request merged**
