### PR TITLE
Separated Lint tests

### PR DESCRIPTION
**Pull request by yvaucher**

### CODE REVIEW

**Comment by legalsylvain** [comment]
:+1:
Thanks.

**Comment by yvaucher** [comment]
@legalsylvain You know why there is twice the env defined here?

This might need some adjustment

Shouldn't I put only once the  `VERSION="8.0" LINT_CHECK="1"` line ?

**Comment by legalsylvain** [comment]
I think I did a mistake initializing the Travis file.
You can remove the second 'env' part.

**Comment by yvaucher** [comment]
@legalsylvain Ok, done

**Comment by pedrobaeza** [comment]
:+1:

**Pull request merged**
