### PR TITLE
11.0 mig pos margin

### PR DESCRIPTION
**Pull request by cvinh**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please squash together adjacent "OCA Transbot.." commits using https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests

**Review by chienandalu — COMMENTED** [review]
~~It'd be nice to have this info in the report as well~~

**Review by legalsylvain — APPROVED** [review]
> It'd be nice to have this info in the report as well

Hi @chienandalu I did'nt understood your remark. could you be more precise ? Thanks.

@invitu : Thanks for porting this module.

**Comment by chienandalu** [comment]
Sorry, I can't recall it right now :sweat_smile: I think I was referring to having that info in the pos order report.

**Comment by legalsylvain** [comment]
Indeed, it could be a great improvment. (even if I personnaly don't use such reports, because performance are horrible).

@chienandalu, otherwise is it OK ?

@invitu, are you ok to add such feature ?
- if no, could you add a remark in the roadmap part, and it will be done in another PR and we can merge that PR
- if yes, I think you have to 

1. overload report.pos.order (https://github.com/odoo/odoo/blob/11.0/addons/point_of_sale/report/pos_order_report.py#L8)
* adding ``total_margin`` field as fields.Float
* add ``sum(l.margin) as total_margin`` in select function

2. overload the xml view (https://github.com/odoo/odoo/blob/11.0/addons/point_of_sale/views/pos_order_report_view.xml#L3)
and add ``total_margin`` field in pivot and or graph view.

**Comment by chienandalu** [comment]
Sure, otherwise is ok :slightly_smiling_face: 

(I'd say it's not strictly necessary to add it to the pivot xml view, since it will be available in filters/groups of the report model)

**Review by chienandalu — APPROVED** [review]

**Comment by pedrobaeza** [comment]
For merging this, the missing feature should be added to the roadmap, isn't it?

**Comment by legalsylvain** [comment]
> For merging this, the missing feature should be added to the roadmap, isn't it?

yes, depends if @invitu want to add this feature or not. Wait to see what he says.

**Comment by cvinh** [comment]
I added it in another module, I can commit it in this one
Hold on...

**Comment by cvinh** [comment]
Hummm... I added margin rate that is much more interesting than total margin (our customer wants to see the biggest margin rates to rate his products)...
Hold on...

**Comment by cvinh** [comment]
Do I have to fix that ?
======== Testing test_flake8 ========
pos_margin/report/pos_order_report.py:13:80: E501 line too long (95 > 79 characters)

**Comment by pedrobaeza** [comment]
Yes if you want a green Travis status, which is mandatory.

**Comment by cvinh** [comment]
@pedrobaeza is it safe to insert a carriage retrun in a sql query ? I've never seen that in Odoo's code

**Comment by cvinh** [comment]
I rebased and force updated

**Comment by pedrobaeza** [comment]
> @pedrobaeza is it safe to insert a carriage retrun in a sql query ? I've never seen that in Odoo's code

Yes, no problem to do it.

**Comment by chienandalu** [comment]
Seems that `pos_loyalty` tests are failing :confused:

**Comment by pedrobaeza** [comment]
Is it failing on main branch also?

**Comment by chienandalu** [comment]
Ok, I see this commit from @legalsylvain https://github.com/OCA/pos/commit/5cabb26b7eff2c358e7f0a747f6e718dea415bcf so maybe @invitu should rebase his branch in order to refresh his HEAD

**Pull request merged**
