### PR TITLE
[ADD] new module pos_order_new_line to allow cashier to force to create a new line

### PR DESCRIPTION
**Pull request by legalsylvain**
### Description 

This module extends the functionality of point of sale module, to allow to force Point of sale to create a new order line, when selecting a product previously selected.

That can be usefull, if you want to sale the same product with different prices and or discount. For exemple :

- You sell carrots, and some carrots are quite old, and you want to apply discount to a part of the products. (but not all the products)

- You want to manually apply some discount like : "2 Coca cola sold, the third will have a 10% discount".

### Usage

* Open the Point of sale
* Select a product
* Click on 'New line'

image

* Select again the same product
-> A new line will be created.

### CODE REVIEW

**Comment by LESTRAT21** [comment]
I did a functional review with : 
- many new lines with quantity changes or discounts : ok !
- display of these new lines in the ticket (html or pdf) is ok
I installed your new module. Thanks for it @legalsylvain  !

**Review by LESTRAT21 — APPROVED** [review]
I did a functional review with :
- many new lines with quantity changes or discounts : ok !
- display of these new lines in the ticket (html or pdf) is ok
I installed your new module. Thanks for it @legalsylvain !

**Review by quentinDupont — APPROVED** [review]
Functional review, works perfectly :heavy_check_mark: 
Can you just add to documentation : "Add `NewlineButton`   in 'Important Buttons" in PoS settings ?"

**Comment by legalsylvain** [comment]
>  Can you just add to documentation : "Add NewlineButton in 'Important Buttons" in PoS settings ?"

The Important Button is a configuration of another OCA module,  ``pos_minimize_menu`` that is installed (as all other 16.0 pos module, in the runboat). The configuration is described here : 

https://github.com/OCA/pos/tree/16.0/pos_minimize_menu#configuration

**Comment by quentinDupont** [comment]
> > Can you just add to documentation : "Add NewlineButton in 'Important Buttons" in PoS settings ?"
> 
> The Important Button is a configuration of another OCA module, `pos_minimize_menu` that is installed (as all other 16.0 pos module, in the runboat). The configuration is described here :
> 
> https://github.com/OCA/pos/tree/16.0/pos_minimize_menu#configuration

oooh ok :)

**Pull request merged**
