### PR TITLE
[FIX][8.0] hw_telium_payment_terminal - python3 syntax to prepare migration

### PR DESCRIPTION
**Pull request by azmeuk**
This PR is mostly harmless. It is about adopting python 3 syntax for `print` and `except` so the linter tools of my editor will not cry.

If it is ok with you, I would like to apply some tools like `black` in another pull request. What do you think about that?

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This is totally incorrect, as this module is for 8.0, which is Python 2. If you want to adapt the module for the image corresponding to 11.0, do it on that branch.

**Comment by azmeuk** [comment]
The code is totally compatible with python 2, it does not change anything about how things work. The current posbox images work with Odoo 8, and thus I need to work on `hw_telium_payment_terminal` on the branch `8.0`, I have already proposed a pull request #371 and it was accepted.

My editor linter work with python3 by default, and I just want it to stop yelling at me.

@pedrobaeza Please reconsider my pull request.

**Comment by pedrobaeza** [comment]
Sorry, but you can't simply change that as expect to work on Python 2. There's a trick doing `from __future__ import print_function` for the print function for example. Any way, as said, this is not valid as it is.

**Comment by azmeuk** [comment]
I am a regular open source code contributor, and i am used to how open source communities work. I generally do not argue on pull request refusals, but honestly, I do not get you point here. If branch `8.0` was unsupported, or if my pull request had side-effects I did not consider, I would have understand.

- If you take time to check the code, and to test it in real conditions (what I did, obviously) you will see that it work on python2. I am not even using python3 myself. This is just about making development tools more comfortable. Please have a look at the few `print` calls this PR does, if you find anything wrong, I can totally accept I made a mistake. However, none of them use anything that would behave differently with `print` as a statement or a function.
- The odoo version I work with is 8.0, and I cannot change that. I am willing to improve this module in other ways in the future.
- There is obviously a need since I am expressing it, and again, a short look at the code will convince you that there is absolutely no impact on other users.
- I am not here to provoke your authority on the project, or make you loose your time, I am just doing my best to help improving it.

**Comment by pedrobaeza** [comment]
This is not a question of 8.0 being not supported. It's simply that the code doesn't work. Have you even checked my comment about the import of future function? I can assure you that it doesn't work in real Python 2 environments.

And the reason for the change about "My IDE complains about it" is not usually enough for changing something. Any way, the main problem is not that one, but incorrect code. I can reopen this PR, but won't be merged for sure unless it's fixed and 2 reviewers support your vision, which I don't think it's going to happen in such old version.

**Comment by rousseldenis** [comment]
@azmeuk I understand @pedrobaeza point of view as python3 is supported >= 11.0 of Odoo. We have to do same.

That apart, @pedrobaeza this is a test I've done :

image

So, that code works and is correctly built-in python2.7 (which is Odoo requirement in v8).

If it eases migration, I'm not against that modification. For the titile, I'd prefer 'Prepare python3...'

**Comment by azmeuk** [comment]
@pedrobaeza Thank you for the details. I have read your comment about the import of future function, I know that there is differences between `print` function and `print` statement, but just not in this patch. I still cannot understand how you can assure me that it does not work, since I am using it in a production environment.

Can you show me an example of environment where this very code will be unusable, so I can better understand your position?

I would like to have other people views on this, so reopening this might be a good idea.

**Comment by pedrobaeza** [comment]
The problem is that 8.0 can work on Python 2.5, not only on Python 2.7, where indeed "new" format works:

https://stackoverflow.com/questions/7075082/what-is-future-in-python-used-for-and-how-when-to-use-it-and-how-it-works

**Comment by rousseldenis** [comment]
And a remark more about this :

@azmeuk print() in python2 works for strings but behaviour is different for:

Python2:
```python
print(1, 2)
(1, 2)
```

Python3:
```
print(1, 2)
1, 2
```

So be careful with that usage.

**Comment by azmeuk** [comment]
@pedrobaeza It does make differences on earlier python versions, but not in 2.7, as far as the code in this PR is concerned. Odoo 8 installation documentation sets [python 2.7](https://www.odoo.com/documentation/8.0/setup/install.html#installing-dependencies) as its requirement.

@rousseldenis I know there are some behavior differences, but my point is, this PR is not concerned since it only prints strings.

**Comment by pedrobaeza** [comment]
@azmeuk OK about Python 2.7. I have mixed old versions.

Please rebase as I have fixed Travis template being old.

**Comment by azmeuk** [comment]
It is done.

**Comment by pedrobaeza** [comment]
hw_telium_payment_terminal/test-scripts/telium-test.py:169:80: E501 line too long (80 > 79 characters)

**Comment by azmeuk** [comment]
This is done. Do you want me to also fix this ones?
```
************* Module hw_telium_payment_terminal

hw_telium_payment_terminal/__init__.py:1: [C7902(missing-readme), ] Missing ./README.rst file. Template here: https://github.com/OCA/maintainer-tools/blob/master/template/module/README.rst

************* Module hw_telium_payment_terminal.__openerp__

hw_telium_payment_terminal/__openerp__.py:1: [C8201(no-utf8-coding-comment), ] No UTF-8 coding comment found: Use `# coding: utf-8` or `# -*- coding: utf-8 -*-`

hw_telium_payment_terminal/__openerp__.py:24: [C8103(manifest-deprecated-key), ] Deprecated key "description" in manifest file

************* Module hw_telium_payment_terminal.controllers.main

hw_telium_payment_terminal/controllers/main.py:1: [C8201(no-utf8-coding-comment), ] No UTF-8 coding comment found: Use `# coding: utf-8` or `# -*- coding: utf-8 -*-`
```

**Comment by pedrobaeza** [comment]
You can rebase here as well.

**Comment by azmeuk** [comment]
This is done.

**Review by rafaelbn — APPROVED** [review]

**Review by fmdl — APPROVED** [review]

**Review by rousseldenis — APPROVED** [review]

**Comment by azmeuk** [comment]
What is needed now to merge this pull request?

**Comment by azmeuk** [comment]
Thank you!

**Pull request merged**
