### PR TITLE
[9.0][FIX] pos_payment_terminal

### PR DESCRIPTION
**Pull request by azmeuk**
This is a port of #371 for branch `9.0`.

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Code review

**Comment by rafaelbn** [comment]
Please @azmeuk sign CLA thanks

**Comment by rousseldenis** [comment]
@azmeuk pos_payment_terminal is not migrated to 9.0... I'm doing it

**Comment by azmeuk** [comment]
> Please @azmeuk sign CLA thanks

I just sent my signature by email.

**Comment by azmeuk** [comment]
If #389 is merged, this PR will be useless.

**Comment by azmeuk** [comment]
#389 has been merged. I close this one.

**Comment by azmeuk** [comment]
Oops, it was actually #245 that has been merged.

**Comment by rafaelbn** [comment]
Hi @azmeuk , I think you can close this PR and review https://github.com/OCA/pos/pull/389 . Isn't it?

**Comment by azmeuk** [comment]
Yes @rafaelbn. I close this one, I review #389 as soon as I have a bit of time to spend on it!

**Pull request closed without merging**
