### PR TITLE
[12.0][FIX] pos_payment_change Add missing unlink access for Point Of Sale:User

### PR DESCRIPTION
**Pull request by r-sierra**
See https://github.com/OCA/pos/issues/556

### CODE REVIEW

**Comment by ivantodorovich** [comment]
Not sure it's a good idea to add this permission. It will have much more impact than you want.

Instead, what about using `sudo()` to remove the statement?

**Comment by r-sierra** [comment]
@ivantodorovich  Branch has been updated to use `sudo`, thanks for the suggestion.

**Comment by ivantodorovich** [comment]
Awesome ☺️ thanks!
One last thing, could you squash the commits into a single one with a meaningful commit message?

**Comment by r-sierra** [comment]
@ivantodorovich Commits squashed and ammended

**Review by ivantodorovich — APPROVED** [review]

**Comment by ivantodorovich** [comment]
fast-tracking simple fix

/ocabot merge minor

**Pull request merged**
