### PR TITLE
[MIG] pos_default_partner: Migration to 15.0

### PR DESCRIPTION
**Pull request by tupaq**

### CODE REVIEW

**Review by etobella — APPROVED** [review]
Works as expected

**Comment by legalsylvain** [comment]
@bealdav : could you review the migration of the module you shared ?
thanks !

**Review by ivantodorovich — APPROVED** [review]
Lg

**Comment by ivantodorovich** [comment]
@tupaq could you rebase and fix pre-commit?
That's the only thing that's blocking the PR AFAICS

**Comment by tupaq** [comment]
> 

Ok @ivantodorovich. rebased and fix pre-commit

**Comment by ivantodorovich** [comment]
I think there's some issue with your last rebase, because I see some commits for other modules that shouldn't be here.
Could you take care of it? Make sure you pull latests changes from `15.0` before rebasing

image

**Comment by etobella** [comment]
CAn you review the problem? @tupaq

**Comment by tupaq** [comment]
> CAn you review the problem? @tupaq

Revised and corrected.

**Comment by HaraldPanten** [comment]
@etobella @ivantodorovich could you merge?

**Comment by etobella** [comment]
There are some merge commits here... Can you rebase and the push force?

**Pull request closed without merging**
