### PR TITLE
[15.0][MIG] pos_picking_delayed: Migration to version 15.0

### PR DESCRIPTION
**Pull request by stefan-tecnativa**
cc@Tecnativa TT38322

@chienandalu @CarlosRoca13 please review!

### CODE REVIEW

**Comment by legalsylvain** [comment]
hi @stefan-tecnativa. could you take a look on the red CI ? 
thanks !

**Comment by pedrobaeza** [comment]
@stefan-tecnativa what about this one?

**Comment by stefan-tecnativa** [comment]
> @stefan-tecnativa what about this one?

I'm taking a look

**Comment by pedrobaeza** [comment]
@stefan-tecnativa seeing the task, we don't need this module anymore, so closing this.

**Pull request closed without merging**
