### PR TITLE
[ADD] new module 'pos_invoicing'

### PR DESCRIPTION
**Pull request by legalsylvain**
This module affect only back-office mode of PoS. (because in V7, invoices is not available in front-office).

With this module : 
- if you use "invoice" button, on a paid pos.order : 
  - The invoices is marked as non payable. (this is a fix, because by default, in point_of_sale module you can create a payment for an invoice that was paid in Point Of Sale);
  - When the session is closed, the invoice is marked as 'paid'. (The account move line are reconciled);
- You can now use "invoice" button on an 'draft' pos.order : 
  - In that case, it is possible to pay after the invoice created;

Regards.

(Coverage of this module : 80%)

### CODE REVIEW

**Comment by legalsylvain** [comment]
I close this after a lot of month without any review.

**Comment by rafaelbn** [comment]
Hi @legalsylvain please reopen, we will review it. Thanks

**Comment by legalsylvain** [comment]
Ok. FYI, it's an V7 module. I'll port it in V8 in a while.

**Comment by rafaelbn** [comment]
OK, thanks.

**Comment by rafaelbn** [comment]
@legalsylvain there is not runbot for testing

**Comment by legalsylvain** [comment]
Hi @rafaelbn , I rebased my PR. runbot is now available for test.
kind regards.

**Comment by legalsylvain** [comment]
hi @rafaelbn any news ? Regards.

**Pull request closed without merging**
