### PR TITLE
[14.0] [mig] pos_default_partner

### PR DESCRIPTION
**Pull request by fshah-initos**

### CODE REVIEW

**Comment by fshah-initos** [comment]
@ValentinVinagre can you please add reviews here?

**Comment by fshah-initos** [comment]
@etobella It would be nice if you could review the PR.

**Comment by fshah-initos** [comment]
It would be nice if we could get the reviews here.

**Review by etobella — APPROVED** [review]
Functional test done

**Review by dsolanki-initos — APPROVED** [review]
LGTM.
Functional Test and code review.

**Review by chienandalu — APPROVED** [review]
/ocabot merge nobump

**Comment by etobella** [comment]
@chienandalu @OCA-git-bot was not executed. Can you try again please :wink:

**Comment by fshah-initos** [comment]
@chienandalu Can you please try again to merge this PR?

**Comment by fshah-initos** [comment]
@chienandalu It would be great if you could try to merge it again.

**Review by ivantodorovich — APPROVED** [review]

**Comment by chienandalu** [comment]
Let's see now :)

**Pull request merged**
