### PR TITLE
[FIX] Allow to inherit CreateOrderButton component

### PR DESCRIPTION
**Pull request by flachica**
Allow inheritance of this component. Without the return you cannot apply the extension

### CODE REVIEW

**Review by chienandalu — COMMENTED** [review]
I see the same issue in the other js file (or you can turn them both into esm modules)

**Comment by flachica** [comment]
> I see the same issue in the other js file (or you can turn them both into esm modules)

Moved to esm modules. Thanks for your review

**Comment by legalsylvain** [comment]
@chienandalu : naive question : what is the interest to use a suffix esm.js ?

**Comment by flachica** [comment]
> @chienandalu : naive question : what is the interest to use a suffix esm.js ?

Make pre-commit understand that it is about typescript

**Comment by legalsylvain** [comment]
Hi. Could you rebase ? (there are conflict)
+ could you use git mv to preserve history in the file ? 

thanks !

**Comment by legalsylvain** [comment]
Hi @flachica. Could you rebase ? so we can merge it.

thanks !

**Comment by flachica** [comment]
Rebased @legalsylvain

**Review by legalsylvain — CHANGES_REQUESTED** [review]
Hi. 
I just saw that you didn't used giv mv. So, old files remains in the static/src/js.
could you fix it ?

**Comment by flachica** [comment]
> Hi. I just saw that you didn't used giv mv. So, old files remains in the static/src/js. could you fix it ?

Sorry, I tried to do it correctly just now.

**Review by legalsylvain — APPROVED** [review]
/ocabot merge patch

**Comment by legalsylvain** [comment]
hi @flachica. the test on pos_order_to_sale_order_sale_financial_risk is failing on CI. Did you reproduced the bug locally ?

**Comment by flachica** [comment]
> hi @flachica. the test on pos_order_to_sale_order_sale_financial_risk is failing on CI. Did you reproduced the bug locally ?

Ups, I don't use this addon

**Pull request closed without merging**
