### PR TITLE
16.0 mig pos_to_weight_by_product_uom (from 12.0)

### PR DESCRIPTION
**Pull request by legalsylvain**
### Description

At the moment, when we create a new product and choose the unity of measure **kg**,  we have to tick the checkbox 'To Weigh With Scale' in the Point of Sale part.

We want to speed the process of creating a new product, avoiding filling manually this parameter.

This module adds the field **'To Weigh With Scale'** in UOM categories (set to **false** by default). If checked, all products created with a related Unit will be 'To Weigh With Scale', by default.

### Configure

* active settings "Allow using different units of measure" in Settings > Configuration > Sales >  Quotations and Sales Orders >  Product Features

* During the creation of a category, tick the box 'To Weigh With Scale'.

uom_category_form

Note: During the installation, the UoM Category 'Weight' is checked.

### Usage

You're able to change this field for a specific product (in Sales tab).

product_form

### CODE REVIEW

**Comment by legalsylvain** [comment]
/ocabot migration pos_to_weight_by_product_uom

CC : @quentinDupont, @hparfr

**Review by ivantodorovich — APPROVED** [review]
LGTM

**Review by quentinDupont — APPROVED** [review]
Code review and functional test :heavy_check_mark:

**Pull request merged**
