### PR TITLE
[MIG][15.0] pos_order_to_sale_order 

### PR DESCRIPTION
**Pull request by jromeroarg**
Migrate pos_order_to_sale_order to odoo 15. Tested in odoo 15 community.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks for the contribution.

Please preserve commit history following technical method explained in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0.

If the jump is between several versions, you have to modify the source branch in the main command to accommodate it to this circumstance.

**Comment by legalsylvain** [comment]
Please review previous work : https://github.com/OCA/pos/pull/865

thanks.

**Comment by houssine78** [comment]
@legalsylvain @pedrobaeza I just tested both PR and this one seems legit as the previous is not even installable. Could you unmark this one from being duplicate and close the other PR ?

Thank you

**Comment by houssine78** [comment]
@josepmy does there is a chance to see you respond to the request of Pedro and bring back the commit history ? I could help if needed. 

Regards,

**Comment by josepmy** [comment]
@houssine78 sorry, but respond about?

**Comment by houssine78** [comment]
sorry @josepmy wrong taging

**Comment by houssine78** [comment]
@jromeroarg does there is a chance to see you respond to the request of Pedro and bring back the commit history ? I could help if needed.

Regards,

**Comment by houssine78** [comment]
thanks @jromeroarg ! @pedrobaeza pre-commit is failing with a weird error. does it's related to this PR ?

**Comment by pedrobaeza** [comment]
Run `copier -f update` on the repo for updating to the latest definition (in a separate PR).

**Comment by pedrobaeza** [comment]
Please preserve commit history following technical method explained in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0.

If the jump is between several versions, you have to modify the source branch in the main command to accommodate it to this circumstance.

**Pull request closed without merging**
