### PR TITLE
[MIG][16.0] pos_escpos_status

### PR DESCRIPTION
**Pull request by nwinkelstraeter**
Migration of pos_escpos_status from 14.0

Other than changing the asset definition in the manifest no changes were needed.

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]
LGTM. code review / no test.
@PierrickBrun could you take a look ? 
thanks !

**Review by ivantodorovich — APPROVED** [review]
Strictly code review, LG

**Comment by GabbasovDinar** [comment]
LGTM!

**Review by GabbasovDinar — APPROVED** [review]

**Pull request merged**
