### PR TITLE
[IMP] pos_lot_selection: clone control no longer needed

### PR DESCRIPTION
**Pull request by chienandalu**
- [x] Needs PR https://github.com/odoo/odoo/pull/23698 to be merged, when clone control is
no longer needed for lots.

cc @Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Let's see if they accept the patch...

**Comment by chienandalu** [comment]
Added reserved quant filter to the selector so only unreserved quants are shown.

**Comment by pedrobaeza** [comment]
But this is still pending of the odoo PR, isn't it?

**Comment by chienandalu** [comment]
Yes, no comment from their side yet

**Comment by pedrobaeza** [comment]
Did you put OPW?

**Comment by chienandalu** [comment]
I didn't but I'm opening a new one to speed it up

**Comment by rafaelbn** [comment]
Hi @chienandalu as https://github.com/odoo/odoo/commit/8f39c652c65c81d87503d64eeef0da3e0048ffc9

I think you could rebase and go ahead with this review

Isn't it?

**Comment by chienandalu** [comment]
@rafaelbn No, that's a commit on `11.0`

**Comment by rousseldenis** [comment]
@chienandalu I confirm odoo patch is on v10.

**Comment by chienandalu** [comment]
Sorry, where? I only see it on OCB

**Comment by rafaelbn** [comment]
Hi @chienandalu , Odoo solved in https://github.com/odoo/odoo/commit/8f39c652c65c81d87503d64eeef0da3e0048ffc9

So please go ahead with this PR please :smile:

**Review by rafaelbn — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Not sure this has been merged. @chienandalu please confirm.

**Comment by chienandalu** [comment]
I reviewed this again. That's not the patch involved, but these ones, that fix those first: https://github.com/odoo/odoo/pull/23698/commits

Odoo guys discussed here: https://github.com/odoo/odoo/pull/15735 and decided to not implement it in v10.

It was finally merged in OCB: https://github.com/OCA/OCB/pull/711

So this PR works with an OCB base but not with an Odoo base

**Comment by pedrobaeza** [comment]
What happens then mixing this PR with vanilla Odoo?

**Comment by chienandalu** [comment]
I'd say the functionality would just be lost and the users would go back to the standard behavior.

**Comment by pedrobaeza** [comment]
Yeah, but the module would be useless then, isn't it?

**Comment by chienandalu** [comment]
It'd be less usable, as there was the need to fill the lot for every unit entered (if I remember well)

**Comment by pedrobaeza** [comment]
Well, then I think we shouldn't merge this. It's only something for reducing code in the module, and being an old version, better to stick to full features. We can still use this aggregating the PR in our v10 databases, so I'm closing this, but without deleting branch.

**Pull request closed without merging**
