### PR TITLE
[13.0][MIG] pos_order_mgmt

### PR DESCRIPTION
**Pull request by dalonsod**
Supersedes #487 due to inactivity

### CODE REVIEW

**Comment by dalonsod** [comment]
@legalsylvain @chienandalu could you review? Thanks!

@trinanda I've reused some of the changes of your PR, I should incluye you in the `CONTRIBUTORS` file. If you agree, please tell me your full name and email

**Comment by chienandalu** [comment]
@dalonsod Yes, although I'll have to test it in my local as runbot isn't working currently

**Comment by dalonsod** [comment]
hello @chienandalu have you tested it locally? Unfortunately runbot is still unavailable. Thanks!

**Comment by chienandalu** [comment]
I'm so sorry. I didn't have the time yet :/ I'll  try to rebuild the runbot though

**Comment by cubells** [comment]
When I try to merge this pr with current version with

`gitaggregate -c repos.yaml`

I've got an error:

`fatal: refusing to merge unrelated stories`

So I think there is something wrong with your history.

**Comment by cubells** [comment]
Can you do a rebase?

**Comment by dalonsod** [comment]
@cubells maybe I'm doing something wrong, but I've made `git rebase 13.0` and git tells me that branch is up to date. When PR was made no merge conflicts were detected

**Comment by cubells** [comment]
Have you run `git push -f` to your repo in order to sync with oca pos repo?

**Comment by dalonsod** [comment]
> 
> 
> Have you run `git push -f` to your repo in order to sync with oca pos repo?

Ok, did it and git told me that everything up-to-date

**Comment by dalonsod** [comment]
@legalsylvain @chienandalu since PR creation it's been impossible to test it on runbot, at least for me. I don't think if it's a problem of this PR, or a general issue of this repo (runbot too busy). Is this a normal situation, or could it be solved? Thanks!

**Comment by dalonsod** [comment]
Now it's working, thanks!
@cubells you can test it on runbot

**Review by cubells — APPROVED** [review]
:+1: 

LGTM

Code review and test

**Review by legalsylvain — APPROVED** [review]
thanks to have ported this must have module.

**Review by chienandalu — APPROVED** [review]
Tested at last :smile: Thanks!

**Pull request merged**
