### PR TITLE
[14.0] [mig] pos_product_sort

### PR DESCRIPTION
**Pull request by fshah-initos**

### CODE REVIEW

**Comment by fshah-initos** [comment]
@HaraldPanten can you please add reviews here?

**Comment by fshah-initos** [comment]
Hi @ValentinVinagre It would be great if you can add reviews here.

**Review by HaraldPanten — APPROVED** [review]

**Comment by ValentinVinagre** [comment]
Hi @fshah-initos 
Tested in the runbot, I think the module does not fulfill the sort function. I have created a new product and it does not sort it by name.

captura1

**Comment by ValentinVinagre** [comment]
> Hi @fshah-initos
> Tested in the runbot, I think the module does not fulfill the sort function. I have created a new product and it does not sort it by name.
> 
> captura1

My Bad, work fine 👍🏻 the uppercase sorts before lowercase.

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Pull request merged**
