### PR TITLE
[16.0][MIG] pos_access_right

### PR DESCRIPTION
**Pull request by geomer198**
Migration to 16.0

### CODE REVIEW

**Review by GabbasovDinar — APPROVED** [review]
Code LGTM!

**Comment by hitrosol** [comment]
I activate the **Multi Employees per session** and add Mitchell Admin and Marc Demo as the Allowed Employees.
I set Mitchel Admin to be able to click the button discount, negative quantity,  unit price change, delete Order / Many Orders. and Payment. But for Demo, i disellect all the related checkbox and the result, whenever I change the pos user in front end, I stilll can see the buttons are available.
This behavior is different with the v14.

Hope this can be fixed soon. Have a Great Job...

**Comment by jumeldi74** [comment]
I would like to add some code to enable feature whenever the cashier is changed

**Review by hitrosol — APPROVED** [review]
Let's merge this so @jumeldi74 can add feature for multi employee on top of this PR.

**Comment by ivs-cetmix** [comment]
> Let's merge this so @jumeldi74 can add feature for multi employee on top of this PR.

Hi @hitrosol @jumeldi74
Thank you for your feedback!
We will take on this PR soon to get it merged. 
@jumeldi74 if you have a solution for an issue described above you can suggest your code so we could merge it

**Comment by hitrosol** [comment]
Hi @isserver1, we created PR https://github.com/OCA/pos/pull/987 and added some more features on it, such as: option to allow /disallow user to delete the order line, refund, give access for cash in/out to pos user, etc. 
Maybe you are interested to review that PR so it can be merged ?

**Comment by ivs-cetmix** [comment]
> Hi @isserver1, we created PR #987 and added some more features on it, such as: option to allow /disallow user to delete the order line, refund, give access for cash in/out to pos user, etc.
> Maybe you are interested to review that PR so it can be merged ?

Sure. However according to the OCA rules we must do migration first. And later add new features in new PRs

**Comment by hitrosol** [comment]
if so, can you make the codecov green so it can be approved and merged? @jumeldi74 will make new PR to add features on top of it.

**Comment by ivs-cetmix** [comment]
> if so, can you make the codecov green so it can be approved and merged? @jumeldi74 will make new PR to add features on top of it.

AFAIK codecove is not a mandatory check. Especially when it comes to the migration PR

**Comment by ivs-cetmix** [comment]
hi @legalsylvain I have updated the branch, please try again

**Comment by legalsylvain** [comment]
the last commit looks useless. could you run ``git pull 16.0 --rebase`` to remove it ?

**Comment by ivs-cetmix** [comment]
> the last commit looks useless. could you run `git pull 16.0 --rebase` to remove it ?

done

**Comment by legalsylvain** [comment]
Thanks ! 

/ocabot merge nobump

**Pull request merged**
