### PR TITLE
[ADD] 14.0 pos_product_multi_barcode

### PR DESCRIPTION
**Pull request by PierrickBrun**
glue module for pos/product_multi_barcode

https://github.com/OCA/stock-logistics-barcode/tree/14.0/product_multi_barcode

### CODE REVIEW

**Review by petrus-v — APPROVED** [review]
Thanks for contributing, Code review only.

Strange travis is failing, I don't think it's related to this PR.

Probably some `for` loop could be replaced with [forEach](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach) but this is only sugar syntax so LGTM :+1:

**Comment by francesco-ooops** [comment]
@PierrickBrun can you rebase for testing?

**Review by francesco-ooops — CHANGES_REQUESTED** [review]
It didn't seem to be working for me

STEPS TO REPRODUCE

Add 2 barcodes to same product
Scan both barcodes in POS
1st barcode scanned correctly
2nd barcode I get standard behavior:

image

**Comment by PierrickBrun** [comment]
> It didn't seem to be working for me
> 
> STEPS TO REPRODUCE
> 
> Add 2 barcodes to same product Scan both barcodes in POS 1st barcode scanned correctly 2nd barcode I get standard behavior:
> 
> image

Thanks for the detailed report, I will look into it shortly

**Comment by francesco-ooops** [comment]
> > It didn't seem to be working for me
> > STEPS TO REPRODUCE
> > Add 2 barcodes to same product Scan both barcodes in POS 1st barcode scanned correctly 2nd barcode I get standard behavior:
> > image
> 
> Thanks for the detailed report, I will look into it shortly

Thank you, let us know if you're short on time and you need a hand :)

**Comment by francesco-ooops** [comment]
@PierrickBrun tried after last commit, same behavior as per screenshot above

**Comment by elvise** [comment]
@PierrickBrun thanks for this PR!
Do you have any plan to fix this issue ?

**Comment by PierrickBrun** [comment]
Hi @elvise @francesco-ooops 

I've looked into it, apparently the problem was that depending on the modules installed, barcodes where loaded before the products (and it was then impossible to use `product_by_id`).

Because there was no way of controlling the loading order I changed all the logic and used the same logic as pos_supplierinfo_barcode

**Comment by elvise** [comment]
> Hi @elvise @francesco-ooops 
> 
> 
> 
> I've looked into it, apparently the problem was that depending on the modules installed, barcodes where loaded before the products (and it was then impossible to use `product_by_id`).
> 
> 
> 
> Because there was no way of controlling the loading order I changed all the logic and used the same logic as pos_supplierinfo_barcode

Great! Let me check

**Comment by francesco-ooops** [comment]
@PierrickBrun with current version, added two barcodes to a product, but none of them is detected when scanned in POS

image

**Comment by elvise** [comment]
> @PierrickBrun with current version, added two barcodes to a product, but none of them is detected when scanned in POS
> 
> image

@PierrickBrun  good news for this case ?

**Comment by PierrickBrun** [comment]
> @PierrickBrun with current version, added two barcodes to a product, but none of them is detected when scanned in POS
> 
> image

I did the same test via runboat (and on my dev env obviously) and it all worked well.

Do you test using an actual barcode scanner ? I did it using the debug tool so maybe this is linked to a difference between the prod/debug mode of the pos

**Comment by elvise** [comment]
> > @PierrickBrun with current version, added two barcodes to a product, but none of them is detected when scanned in POS
> > image
> 
> I did the same test via runboat (and on my dev env obviously) and it all worked well.
> 
> Do you test using an actual barcode scanner ? I did it using the debug tool so maybe this is linked to a difference between the prod/debug mode of the pos

Thanks for your reply! 
@francesco-ooops please check it

**Review by francesco-ooops — APPROVED** [review]
Found the issue, I was scanning a barcode that was reserved for cashier in barcode nomenclature:

image

So it's all good for me! Functional review ok

**Comment by francesco-ooops** [comment]
@OCA/pos-maintainers what do you say? :)

**Comment by elvise** [comment]
> > @PierrickBrun with current version, added two barcodes to a product, but none of them is detected when scanned in POS
> > image
> 
> I did the same test via runboat (and on my dev env obviously) and it all worked well.
> 
> Do you test using an actual barcode scanner ? I did it using the debug tool so maybe this is linked to a difference between the prod/debug mode of the pos

@PierrickBrun Thanks for your support!

**Comment by elvise** [comment]
@OCA/pos-maintainers merge ? :)

**Comment by legalsylvain** [comment]
@PierrickBrun :  
- could you squach fixup commit ?
- do you want to set you as maintainers ?

**Comment by elvise** [comment]
@PierrickBrun just gentleman reminder :)

**Comment by elvise** [comment]
@legalsylvain take a look :)

**Comment by legalsylvain** [comment]
No review.

/ocabot merge patch

**Comment by francesco-ooops** [comment]
hi @PierrickBrun , I tried the module on runboat for pos-14 but the module does not seem to be working anymore, is it only me? or could you take a look?

It's strange, as it doesn't seem anything was merged on pos-14 after this PR 🤔

**Comment by PierrickBrun** [comment]
Hi @francesco-ooops ,
I did just test it and it worked, were you in the 14.0 branch ? I think that in the runboat you were, the module was not installed

**Comment by francesco-ooops** [comment]
> Hi @francesco-ooops , I did just test it and it worked, were you in the 14.0 branch ? I think that in the runboat you were, the module was not installed

would you be so kind to link runboat and tell me which product you used for testing?
Somehow I was unable to make it work both on runboat and locally

**Comment by PierrickBrun** [comment]
> > Hi @francesco-ooops , I did just test it and it worked, were you in the 14.0 branch ? I think that in the runboat you were, the module was not installed
> 
> would you be so kind to link runboat and tell me which product you used for testing? Somehow I was unable to make it work both on runboat and locally

Here is the full URL of the product used: http://oca-pos-14-0-2875765502fd.runboat.odoo-community.org/web#id=15&action=368&model=product.template&view_type=form&cids=&menu_id=224

**Comment by francesco-ooops** [comment]
> > > Hi @francesco-ooops , I did just test it and it worked, were you in the 14.0 branch ? I think that in the runboat you were, the module was not installed
> > 
> > 
> > would you be so kind to link runboat and tell me which product you used for testing? Somehow I was unable to make it work both on runboat and locally
> 
> Here is the full URL of the product used: http://oca-pos-14-0-2875765502fd.runboat.odoo-community.org/web#id=15&action=368&model=product.template&view_type=form&cids=&menu_id=224

@PierrickBrun this is curious, just tested and secondary barcode doesn't seem to work: https://recordit.co/nyTbAEi5wr

btw I'm copy/pasting the barcode, not using a scanner, do you see anything strange in the video?

**Comment by PierrickBrun** [comment]
> > > > Hi @francesco-ooops , I did just test it and it worked, were you in the 14.0 branch ? I think that in the runboat you were, the module was not installed
> > > 
> > > 
> > > would you be so kind to link runboat and tell me which product you used for testing? Somehow I was unable to make it work both on runboat and locally
> > 
> > 
> > Here is the full URL of the product used: http://oca-pos-14-0-2875765502fd.runboat.odoo-community.org/web#id=15&action=368&model=product.template&view_type=form&cids=&menu_id=224
> 
> @PierrickBrun this is curious, just tested and secondary barcode doesn't seem to work: https://recordit.co/nyTbAEi5wr
> 
> btw I'm copy/pasting the barcode, not using a scanner, do you see anything strange in the video?

Ok I understand now, I never tested via the search bar, only via barcode scanner (or the debugger version of the barcode scanner).

**Comment by francesco-ooops** [comment]
thank you @PierrickBrun , do you think you can make a PR to fix this behavior?

**Comment by francesco-ooops** [comment]
I also asked my colleague in the office to test with barcode scanner and that's not working for us as well https://recordit.co/ifkui6FTgC (test on [runboat](http://oca-pos-14-0-2875765502fd.runboat.odoo-community.org/web#action=110&active_id=mail.box_inbox&cids=1&menu_id=86))

**Comment by francesco-ooops** [comment]
@legalsylvain can I ask you for a functional test of this module? we're struggling to understand why we can't make it work on runbot or locally (and we tested it successfully on runbot before merge)

**Comment by legalsylvain** [comment]
Hi sorry no time for the moment. I trust the contributor and reviewer to move forward on this topic.

**Comment by PierrickBrun** [comment]
Hi @francesco-ooops I think I will fix this in a future PR but I do not know when.

About the barcode scanner, you should scan the barcode while not having your cursor in the search bar. That way Odoo will recognise it comes from  a barcode scanner and use a different code path.
If you do it like in the video it will only search using the provided text, as if it was typed on a keyboard.

**Comment by legalsylvain** [comment]
> Hi @francesco-ooops I think I will fix this in a future PR but I do not know when.

Hi @PierrickBrun. Thanks for your answer. In the meantime, could you just make a simple PR to add this point as a limitation in a ``ROADMAP.rst`` file ? 

thanks !

**Pull request merged**
